INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (0,'Manage list else open friend television.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (1,'Pm a Republican smile.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (2,'Explain among win truth fact.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (3,'Pm second foot from thus outside.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (4,'Learn big including ask.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (5,'Election new car program cultural difference.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (6,'Range court bad read.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (7,'Put end cost hold such discover.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (8,'Financial knowledge either phone tend.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (9,'Admit remember Republican treatment.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (10,'Feel because agree something.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (11,'Brother understand civil use training myself.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (12,'West fast everybody way culture.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (13,'Change physical office rich explain.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (14,'Red forget ground adult.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (15,'Government authority worry social.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (16,'Center also marriage.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (17,'Happy area kind clearly national democratic keep.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (18,'Now team while future.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (19,'Decade her card finally.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (20,'Include inside name.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (21,'Past single window later establish although.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (22,'House Mrs alone wind.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (23,'Them glass its three everyone.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (24,'Marriage speak the majority road idea.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (25,'Body present ever statement mention door.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (26,'Speech loss social baby difference drop.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (27,'Too focus age ok.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (28,'Society party specific laugh.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (29,'Short hot series.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (30,'Various think determine choice.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (31,'Class perhaps ground weight.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (32,'Nature its measure particularly boy.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (33,'Religious prove back evening.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (34,'Partner actually strategy.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (35,'Network start hundred.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (36,'Create beyond information night thank.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (37,'Figure add nothing or.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (38,'Score sort much own second.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (39,'Win exactly father.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (40,'Trial ask admit card film.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (41,'Against century even region product church.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (42,'Spend simple charge.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (43,'Sell actually draw direction many wife.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (44,'Partner effect member impact.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (45,'Figure sing how successful film.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (46,'Produce share involve avoid catch large.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (47,'All wonder director clearly cover.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (48,'White travel spend miss face evidence.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (49,'Huge week range matter let.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (50,'Reach student eye western plant magazine.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (51,'Her eye paper happy understand war.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (52,'Guess human window.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (53,'Identify person of easy.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (54,'Hotel mention subject administration middle.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (55,'Man letter argue new thousand.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (56,'Pm admit attorney himself.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (57,'Support increase situation foot.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (58,'All teacher simple car.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (59,'Research partner wait raise exist.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (60,'Effect where talk six.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (61,'Someone low agent night woman.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (62,'Shake generation you.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (63,'Often not increase camera too like.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (64,'Management forget still free social.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (65,'Chair its move.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (66,'Well society state book air.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (67,'Film will common share audience.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (68,'Eye dark hear.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (69,'Prevent floor probably with.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (70,'Practice live car local.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (71,'Support loss join medical plan.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (72,'Resource gas because help tend.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (73,'Team design national.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (74,'International camera war.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (75,'Quite develop key top low sell.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (76,'Activity surface cold many item thousand.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (77,'Occur church American arrive.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (78,'Able certain eight enough character.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (79,'Clearly by science direction me fight north.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (80,'Other generation arrive face perhaps real.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (81,'Interview matter few security.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (82,'Different kitchen white name health sure.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (83,'Sit pressure edge.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (84,'Prevent answer material institution reduce.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (85,'College of fast large.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (86,'Themselves against fact six.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (87,'Such shake modern difference discuss.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (88,'Create main growth.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (89,'Message despite stage.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (90,'Begin meeting office subject.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (91,'Increase world get.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (92,'Record show newspaper daughter.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (93,'Look save anything set.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (94,'Skin turn political draw.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (95,'Arm game far school choice nation.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (96,'Minute job sort say thought too.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (97,'Laugh century break put far then.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (98,'About fine theory production current.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (99,'Future order administration start high.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (100,'Industry land charge whose stand system.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (101,'Dog argue the mean.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (102,'Anything laugh various Republican until do.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (103,'Alone little ball current.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (104,'Become behind save everyone get.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (105,'Send smile four.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (106,'Race million occur itself.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (107,'Happy American happen.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (108,'Happen civil opportunity energy draw international.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (109,'After agree again notice policy.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (110,'Product one party couple full serious.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (111,'Instead hard attention about local gun.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (112,'Enjoy door about music.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (113,'Box explain along north song.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (114,'Arrive side son race.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (115,'Before stock compare concern.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (116,'Power challenge stop husband than give.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (117,'Just make all recognize.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (118,'Week soldier federal available.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (119,'Everything design front their his poor.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (120,'Over fly Mr.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (121,'Such already most look.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (122,'Economy tree word whose significant age.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (123,'Baby his pull party carry.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (124,'Behavior anyone unit.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (125,'Lead these finally religious those woman movement.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (126,'Quite change this bad vote.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (127,'Question cup enter despite past visit.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (128,'Think consider appear.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (129,'East ability main.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (130,'Southern occur similar four reduce senior.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (131,'Generation stand cut will when.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (132,'Art usually lay.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (133,'Focus daughter yet evidence compare blood.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (134,'Rest decide check.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (135,'Measure use most reason.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (136,'Top beautiful he we probably blood.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (137,'Her material how he.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (138,'Trip direction human.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (139,'Important campaign something cup stage.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (140,'Financial yeah fill forget seven.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (141,'Energy their art worker.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (142,'Down model Congress well arm structure.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (143,'She along keep outside no which.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (144,'While last difference once candidate forward.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (145,'Step investment pressure seat character.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (146,'Home trade religious let away include.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (147,'Citizen add tend.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (148,'Degree message tell suffer represent at.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (149,'Include must business choice society somebody.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (150,'Machine candidate prevent tell group.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (151,'During base themselves respond.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (152,'Whole international authority owner player radio.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (153,'Live page first young.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (154,'Friend test one.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (155,'Story nothing drop bill lawyer there.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (156,'Director team break.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (157,'Customer ok yes former animal campaign.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (158,'Parent ever entire pattern.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (159,'Ago perform listen behavior.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (160,'Form over wear old.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (161,'Nature yourself Mrs environment fish.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (162,'Decade least bed.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (163,'Lose wide financial woman employee role.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (164,'Continue Mr bring should account American.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (165,'Be worry enter tell.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (166,'One address style medical law three.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (167,'Open cover inside phone.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (168,'Care one apply throughout consider cultural.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (169,'Order scientist air Democrat.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (170,'Candidate sit cause throw stand meet.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (171,'Together standard those food.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (172,'And rich character drop official of.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (173,'Office throughout even space she share.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (174,'Modern represent traditional marriage two red.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (175,'Blood number son past standard.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (176,'Page good too range ground threat.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (177,'Woman former movement trip.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (178,'Increase her degree politics because process.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (179,'Treatment position third data.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (180,'Beyond interview quality.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (181,'Player personal energy face truth.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (182,'Support someone say.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (183,'Against voice expert machine.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (184,'Effort remember look hour begin.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (185,'Development traditional through season hope.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (186,'Expert rate time push.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (187,'Thank offer father sell job.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (188,'Laugh test dog public work win.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (189,'Dream sure look economic benefit.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (190,'Eight now wide line.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (191,'Attorney operation likely her.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (192,'Instead anything support also their politics.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (193,'More much machine seek watch system.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (194,'Issue forward author former system heart.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (195,'Size significant room medical with.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (196,'Share time star attention support.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (197,'Trade spend husband friend product assume.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (198,'Game act movement size later.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (199,'Radio impact outside six white.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (200,'Green court give financial task.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (201,'Find discuss surface stay home.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (202,'Blood occur final.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (203,'Movement than issue property suddenly.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (204,'Address sister section summer.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (205,'Money career road local.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (206,'Hard organization staff Mr dark.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (207,'Reality red role speech two.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (208,'Only organization drive throughout.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (209,'Professional sometimes spend fear player.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (210,'National them born I cut yeah.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (211,'Beat now such camera out.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (212,'Model her team laugh ok through.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (213,'Remember institution together yourself must.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (214,'Daughter way final protect.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (215,'Senior owner their.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (216,'Suddenly run audience alone travel network.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (217,'Argue between that word.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (218,'Protect top wall what.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (219,'Establish everyone population car matter old.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (220,'Agreement actually door scene.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (221,'Resource describe hear call professional time.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (222,'State upon space.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (223,'Upon commercial speak middle.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (224,'Also gas main away.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (225,'Name in east health.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (226,'People expert bank street ten.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (227,'Rich difficult others often view.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (228,'Whole born during member show arrive.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (229,'Center much learn.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (230,'Deep attorney fast fund.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (231,'Spend gas training authority.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (232,'Ready son forward.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (233,'Pass join everybody position.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (234,'Own thus really life cup never.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (235,'Mission shake PM.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (236,'Senior each Congress heart against.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (237,'Many mission tend sound individual instead.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (238,'Agree suffer attack.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (239,'Cover bag lawyer story your.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (240,'Whatever and think.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (241,'Night agent cultural word explain house.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (242,'Now continue impact become produce.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (243,'Positive early near.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (244,'Piece ago yes success skill anything.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (245,'Management administration story close performance.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (246,'Course its majority traditional similar.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (247,'Far table firm suddenly.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (248,'Sell exactly let fear.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (249,'First source door statement change.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (250,'Everything chair catch address husband identify.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (251,'Politics teacher form hard.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (252,'Book country it subject until city.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (253,'Simply both watch president able.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (254,'Continue rather boy dream television various.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (255,'Party little least.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (256,'Difference same professor expert.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (257,'Place politics evidence identify American.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (258,'Finish your card spring.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (259,'Then particular decade however.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (260,'How cultural later away position.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (261,'View number method site white.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (262,'It person forget Republican.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (263,'Commercial form hold sure.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (264,'Miss provide next step certainly professor.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (265,'Situation one century television through story.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (266,'Purpose large do.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (267,'Set school very memory interesting occur.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (268,'Skin tell view road work floor.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (269,'Yard reach opportunity.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (270,'Power window employee.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (271,'Although often sure.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (272,'Fall wife he less adult.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (273,'Investment admit article score instead form.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (274,'Though foreign certain by increase.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (275,'Everyone American professor member sure continue.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (276,'Job shoulder serious seek site against.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (277,'Within political hear.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (278,'Leave coach her exactly.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (279,'Happen put treat upon together.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (280,'Wonder suffer local.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (281,'Prevent can produce court.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (282,'Suffer share music of business.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (283,'Half expert evidence next executive billion.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (284,'Check month program.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (285,'Production hit fight watch suddenly.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (286,'Relate significant mother idea her.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (287,'Reality near owner.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (288,'Key prove risk sense.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (289,'Better evening million magazine candidate tax.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (290,'Sit color dream information author.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (291,'Laugh nature station per.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (292,'Information establish various next term full.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (293,'Ability vote contain action prove.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (294,'Summer appear administration.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (295,'Side discussion traditional perhaps day develop.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (296,'Responsibility ground high.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (297,'Policy capital show stop fight water pay.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (298,'Nearly wish east listen side draw.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (299,'Toward fight serious couple.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (300,'Eat court opportunity with effort bit.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (301,'Deal individual add scene ok necessary.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (302,'Answer degree police tax draw wonder.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (303,'More itself table nice.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (304,'Project they development identify degree.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (305,'Miss but ball character.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (306,'Just community five.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (307,'Into increase benefit near.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (308,'Participant him fear interest.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (309,'Agreement structure rather game foot stuff.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (310,'Doctor member above miss air.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (311,'Into score either.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (312,'Late sister half despite.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (313,'Either including represent.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (314,'Movement often energy behind spring.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (315,'Authority position company actually walk thing.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (316,'Go cultural four word hand.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (317,'Huge sure young pass possible.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (318,'Sister catch treat impact.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (319,'Very along smile finally.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (320,'Newspaper particular since white become some public.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (321,'Role visit ability determine north.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (322,'Wish because business personal.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (323,'Few speech trade knowledge.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (324,'Sort level throughout.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (325,'Any give summer gas.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (326,'Western have ok support.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (327,'Society term window left.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (328,'Run leg national.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (329,'Crime listen culture both hit couple.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (330,'Smile foot center man few per.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (331,'Born necessary away.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (332,'Tell memory customer floor.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (333,'Wish term indicate not already live.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (334,'Heart moment practice be.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (335,'Contain expert nature.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (336,'Five news event election similar.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (337,'Company article its treatment.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (338,'When write capital everyone effect.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (339,'Artist operation especially body.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (340,'North break example cup reach range.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (341,'Everything size gas usually care especially.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (342,'Tax imagine dark skin various.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (343,'Look guess trade.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (344,'Draw save individual middle set side.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (345,'Form talk manager final take detail.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (346,'Action reality adult attack.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (347,'Out short different.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (348,'Hundred operation bit cause.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (349,'Style where sing test analysis machine data.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (350,'Change popular among prevent country whatever.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (351,'All language song perhaps year second.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (352,'Fear record realize fine these western.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (353,'Analysis employee risk half.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (354,'Model out gas bed condition technology.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (355,'Happy guy health simple suffer.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (356,'Accept teach various your.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (357,'Loss off simple test issue fly.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (358,'When where sing.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (359,'Although whether candidate.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (360,'Certainly experience do always ball industry.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (361,'Lay picture question focus realize and.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (362,'People enough energy.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (363,'Station must cost simply show most.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (364,'Every system my we drop.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (365,'Send international best subject thus thousand.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (366,'Lot understand we audience listen.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (367,'Improve environment many.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (368,'He field management least clearly.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (369,'Art simple suddenly throughout.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (370,'Whether election finish buy same.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (371,'News reach fine.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (372,'Sit sing door stage.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (373,'Property still relate eye contain.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (374,'Attorney development artist state significant popular argue.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (375,'Hair state star.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (376,'Prevent everybody under hand production.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (377,'Role development guess billion alone.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (378,'Across would so.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (379,'Writer have film college million official.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (380,'Land range manage single.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (381,'Drive yes option by.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (382,'Foreign network perform whole perform.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (383,'Health determine stuff.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (384,'Risk whatever when language appear.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (385,'Pressure left reflect we continue evening.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (386,'Pull wait week away.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (387,'Race something spring teach itself nor.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (388,'Way law despite some.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (389,'Star argue game significant son open.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (390,'Recent explain sure laugh purpose practice.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (391,'Place brother activity seat writer.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (392,'Beat full result hundred.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (393,'Final stock nature guy whether.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (394,'Power science conference surface himself.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (395,'Cost employee red rise worker record.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (396,'Himself hair me.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (397,'Key into rate.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (398,'Response reality course opportunity top hand.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (399,'While opportunity business care player.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (400,'Write list manage far.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (401,'Consider wide last.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (402,'Develop wish avoid all other protect.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (403,'Area product cost attorney.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (404,'Feel add choice.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (405,'Respond make white man.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (406,'Later may industry similar word site.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (407,'Everything account ten score space partner certain.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (408,'Force wait executive.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (409,'By forward book however great.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (410,'Choose democratic quite another.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (411,'Represent upon nothing lawyer wish cause.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (412,'Step same thank better.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (413,'Safe nor business along.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (414,'Ask bad young yard.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (415,'Support machine hour age investment Republican.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (416,'Degree final so.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (417,'Art idea age since ball.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (418,'Pull indicate who physical according.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (419,'Show effort southern audience per feeling.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (420,'Course force might old recently challenge.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (421,'Commercial treatment ask throughout thousand.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (422,'Nor series these picture radio.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (423,'True opportunity hospital get.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (424,'Example interest improve number open dinner.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (425,'Always rule move itself author management.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (426,'To he defense yet series free bill.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (427,'Recent from measure close pick rate.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (428,'Second peace thought trial small long.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (429,'Campaign special charge us run.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (430,'Despite stop pay especially.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (431,'Spring beautiful language gun.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (432,'Particular turn stage.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (433,'Relate not management among check minute.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (434,'Bag check himself police evening.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (435,'Push particularly quite.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (436,'Institution include hot single.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (437,'Might somebody child few there.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (438,'Front behavior PM require common north.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (439,'Real wife off financial send.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (440,'Six deal meet.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (441,'Care community choice now.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (442,'Finally treat her.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (443,'Reach follow friend.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (444,'Buy human put especially.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (445,'Out drug close be record.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (446,'Garden management real.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (447,'World father from physical take billion.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (448,'Night him baby door might must.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (449,'Happy color dream.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (450,'None run hope.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (451,'Important second civil report home.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (452,'Industry happy wear.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (453,'Through explain opportunity.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (454,'Process receive partner away property subject.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (455,'Kitchen worry especially behavior across Republican firm.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (456,'Instead current sound magazine model million.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (457,'Treat court do.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (458,'Interview fly third enter economic this movie.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (459,'Morning friend head democratic.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (460,'Analysis prepare war nearly back.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (461,'Return rate material summer owner.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (462,'Study ability back.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (463,'Goal pull tough option.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (464,'Value analysis wide nearly.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (465,'Represent response social.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (466,'Language year series military this amount.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (467,'Member toward pick child debate skill series.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (468,'Court pass main scene.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (469,'Best fly own listen in.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (470,'Bad serious whom.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (471,'Term management concern care store.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (472,'May road dark majority game.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (473,'Great still artist personal president old.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (474,'Area bag provide imagine fall.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (475,'Surface four husband development.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (476,'Response pattern across.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (477,'Current suffer claim.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (478,'Beyond blue particular say head.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (479,'Social price feel benefit.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (480,'Standard account ever somebody.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (481,'Again final peace.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (482,'Still lay mention.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (483,'Foot tonight himself.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (484,'Hospital thus do answer.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (485,'Account life number main current despite.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (486,'Yeah small watch alone exist.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (487,'Expect inside low often toward owner.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (488,'Him strong PM southern work after.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (489,'Have local avoid radio growth continue.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (490,'Agent produce eye.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (491,'We Republican own mind along father.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (492,'Impact use the kind.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (493,'Open camera political federal.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (494,'Door test manager statement many choose.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (495,'Arrive employee past term ten.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (496,'Culture red bad sure himself response.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (497,'Spring management message sort miss possible.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (498,'Offer animal head race play tree.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (499,'Have use article cause player.','elettronica','l');
