INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (0,'But authority spring camera great individual.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (1,'Science car government.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (2,'Vote identify senior together fine.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (3,'The least arrive ok.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (4,'Fight threat travel go few nor.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (5,'Idea laugh debate hit store read.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (6,'Home admit this.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (7,'Authority our left against commercial determine.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (8,'Address mouth PM.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (9,'Cost yard still pressure sort.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (10,'Cup full arm.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (11,'Party half create gun.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (12,'Bit subject every state.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (13,'Change onto morning where.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (14,'Cell throughout question.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (15,'Cell difference Republican water here.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (16,'Reduce can various past certain.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (17,'Little give despite example.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (18,'Drug pretty data.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (19,'Serve region hit human.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (20,'Above exist expect book suddenly message.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (21,'Simple place area.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (22,'Director increase moment necessary page.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (23,'For sound believe.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (24,'Give small risk fear watch.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (25,'Line believe he together.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (26,'Away second send property.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (27,'Too rather within future hundred power.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (28,'People local account job say each.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (29,'Drug what message rich.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (30,'Charge base crime fill interesting pretty.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (31,'Moment play next participant minute.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (32,'Provide at however onto professional.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (33,'Significant easy economic.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (34,'Out mention positive.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (35,'Should child production kind camera.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (36,'Guess take purpose.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (37,'Perform minute address live.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (38,'Itself house top.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (39,'Walk recent main care.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (40,'If image almost piece majority.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (41,'American structure wall present.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (42,'Pm the reduce.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (43,'Run lose successful laugh possible forget.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (44,'Only person pay.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (45,'Meeting enough exist.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (46,'Improve now discover sometimes least join.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (47,'Fact situation international piece style.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (48,'Mission western his social.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (49,'Anyone under statement begin.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (50,'Now who research check create mother.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (51,'Require station their writer never.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (52,'Religious civil cell.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (53,'Turn fine real war decide keep.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (54,'So good church apply.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (55,'Performance according argue half movie give.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (56,'Always economic do actually you public.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (57,'Information I parent exist.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (58,'For fill while close friend until.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (59,'Measure send clear activity show available.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (60,'Professor there bank visit cell.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (61,'Become position way.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (62,'Hospital race article customer fund.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (63,'Truth letter whose five.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (64,'Quickly career often.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (65,'Science return million her measure already.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (66,'Final across effect reach.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (67,'Evening south now street daughter.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (68,'Fill population manage.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (69,'Cut claim mean sport live yourself.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (70,'Either value rest with kind.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (71,'Will election key.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (72,'Without economy win.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (73,'Population serve challenge detail always.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (74,'Next answer necessary seek work.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (75,'Scene peace exactly.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (76,'Enjoy threat budget evening whatever season.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (77,'Mr accept hard.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (78,'Control need find yet.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (79,'Rest unit lay.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (80,'Democratic series campaign.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (81,'Owner hot hair.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (82,'Main TV different society place.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (83,'Interest help build.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (84,'Sport so prevent east less station.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (85,'Month break thought near hear on.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (86,'Else ten establish audience group sound.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (87,'How huge wind may check above.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (88,'Reflect shake reflect now.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (89,'Letter forget order.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (90,'They huge various these property maybe.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (91,'No then just quickly.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (92,'Beyond fact truth people long social.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (93,'Issue safe organization seven phone.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (94,'Policy describe learn century.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (95,'Himself pretty anything.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (96,'Brother pressure best coach them.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (97,'Various student mean guy bag.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (98,'Until case yard with born eight.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (99,'Play similar tell.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (100,'Much happy later loss often cause.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (101,'Clear fund financial care.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (102,'Seek medical news seem.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (103,'Customer away know north subject.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (104,'Three choose wait chair international.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (105,'Specific decide herself side send.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (106,'How security talk case.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (107,'East spring too.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (108,'Weight section TV none event thing.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (109,'Drop real pretty.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (110,'Factor subject role professor cut.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (111,'By customer inside none ok.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (112,'Head subject middle respond.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (113,'Seek around fly.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (114,'Once boy air physical toward.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (115,'Oil art many leg unit this.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (116,'Wonder yet spend.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (117,'System quite threat.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (118,'Into company story participant decision.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (119,'Same knowledge call positive.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (120,'Relationship which western recognize not.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (121,'Even none set across specific.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (122,'Main through guess result hear whatever.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (123,'Visit star available stand.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (124,'Which suffer education drive full.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (125,'Other management need go player.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (126,'Help who environmental huge century.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (127,'Wrong region space common wind hope.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (128,'Million third eat war.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (129,'Direction where industry board its bar.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (130,'Structure necessary station.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (131,'Range fill leader standard politics employee.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (132,'Follow beautiful issue story natural.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (133,'Author it whatever technology election.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (134,'Land economy international buy send.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (135,'Hair yes camera foot success.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (136,'Large grow enough method admit.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (137,'With full party.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (138,'Easy evening wish.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (139,'Parent become property current oil.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (140,'About deep company wrong security none.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (141,'Congress you poor include.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (142,'Leg beat society.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (143,'Total fill accept there window.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (144,'See quality course subject simple.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (145,'Least itself own finish student.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (146,'Necessary view industry accept blue.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (147,'Thousand candidate all fly.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (148,'Here suddenly system subject.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (149,'Home professor four us hot difference.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (150,'Clear nor marriage guess ball.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (151,'Do ago clear.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (152,'Lose marriage live perhaps.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (153,'Mission nearly trial skin.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (154,'Those agreement mouth center.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (155,'Knowledge term edge resource.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (156,'Hot require never.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (157,'Try fund bar which far once.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (158,'Again forward night.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (159,'Responsibility now Democrat.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (160,'Should chance pretty.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (161,'Standard what already understand contain just.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (162,'Rock cost wife first year night.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (163,'Price important adult.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (164,'One Mrs suddenly.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (165,'Necessary I behind wait research ground.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (166,'Turn fact I.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (167,'Computer their fish environment affect.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (168,'Level quickly audience analysis.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (169,'Gun result development though.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (170,'Service market shake.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (171,'Similar race pretty standard know.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (172,'Hundred brother section truth fire.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (173,'Strong involve pattern age.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (174,'Cut might run.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (175,'Race for positive performance during visit.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (176,'Natural might voice.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (177,'Hear check life western.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (178,'Region trade race human past color.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (179,'Child happy sign manage.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (180,'Game company suffer like reality.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (181,'Stop professional they carry here federal.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (182,'Energy every on.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (183,'Air drive ask start.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (184,'Career fund itself finally decision.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (185,'Son black result.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (186,'Face success sport since.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (187,'Sport community nature along.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (188,'Into book source after plan.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (189,'Various almost capital together hear visit.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (190,'Ten guy reflect.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (191,'Kitchen wonder occur war possible crime.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (192,'Wear ability growth single or.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (193,'Likely five indicate.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (194,'Decision member important.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (195,'Professor old everyone sport nature.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (196,'Control tree south whether find century.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (197,'Traditional television church same war coach.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (198,'A state threat people character.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (199,'Try reveal themselves movie happen.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (200,'Whole dinner send whether focus.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (201,'Decision east itself may concern well.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (202,'Radio politics toward act from.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (203,'Really arm team.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (204,'Middle paper quite lead doctor they.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (205,'Three card PM candidate cup.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (206,'Animal hit stop true such own.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (207,'Four agree table sing.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (208,'Magazine operation resource fact education still.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (209,'Area view difference special prevent.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (210,'Style candidate pressure eat large.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (211,'Kitchen trip police.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (212,'Remember similar month.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (213,'Medical voice itself.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (214,'Age street answer go.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (215,'Note step there.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (216,'Good what set degree share.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (217,'Main blue ago within simple record.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (218,'Strong cup stuff can.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (219,'Generation one morning way policy.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (220,'Task five expect everything.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (221,'Form factor statement magazine herself week.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (222,'Present military oil number pretty others.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (223,'Almost film worry year question.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (224,'Tree nothing individual paper water.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (225,'Concern often civil quality price.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (226,'Parent growth field yes.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (227,'Oil detail rise leg.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (228,'Miss perform box thing production citizen.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (229,'International fast such individual.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (230,'Else store high bring.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (231,'On two machine note build where.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (232,'Adult talk authority.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (233,'Interest PM impact.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (234,'Long reason professional low attorney.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (235,'Wonder yes wall.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (236,'Commercial her detail usually maintain eye.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (237,'Science Mr conference.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (238,'Morning possible herself according.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (239,'Itself interview mother over administration share.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (240,'Practice remain any marriage management.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (241,'Spend move imagine magazine someone.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (242,'Direction simply property wait listen church.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (243,'Explain smile focus identify lay.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (244,'Of government bar.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (245,'Value practice relationship which prepare.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (246,'Central rock join smile manage either.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (247,'Very ground away fall month call.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (248,'Able strong be attorney certainly impact.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (249,'Color but society.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (250,'Home notice simply.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (251,'Process treatment product over.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (252,'Force card sound program either.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (253,'Authority sea kitchen wish hear.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (254,'Large physical side.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (255,'Early especially discussion.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (256,'Suffer foreign five.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (257,'Heart Congress trip.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (258,'Traditional appear way.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (259,'Military subject community practice class keep.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (260,'Serve far trial forget health protect.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (261,'Police worker market.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (262,'Sit already bill computer.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (263,'Company leave owner part become.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (264,'Add across according after according fast.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (265,'Serve most score threat floor effect.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (266,'Do son hear dog may.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (267,'Interview the mean wear between main forward.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (268,'Quickly from purpose though.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (269,'Material arrive position watch.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (270,'Stand price decide.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (271,'Home where leave kitchen according.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (272,'Republican agree worry statement officer compare.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (273,'Security describe without.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (274,'Summer teach he human.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (275,'Course often hot.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (276,'Face dog your meeting.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (277,'How news to.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (278,'Turn fill audience.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (279,'Born read field how among decade.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (280,'Article accept how black yeah similar.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (281,'Enough American develop daughter along success.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (282,'Prepare religious teach stock could fast.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (283,'There trade couple church.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (284,'Republican none stage brother soon sit.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (285,'Bring trial worker painting show.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (286,'Popular church standard computer heart.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (287,'Feeling only and base face.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (288,'Drive morning contain.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (289,'Well task score before ball series.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (290,'Bit skill turn ball fight.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (291,'Chance another mention foot generation.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (292,'Myself write again.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (293,'Central power maintain yard stuff fill.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (294,'Level commercial ago.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (295,'Southern idea general whom ahead.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (296,'Imagine pull agent hope.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (297,'Raise hold so head lay turn.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (298,'Letter factor choice national administration true.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (299,'Game loss test business decide art.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (300,'This easy mother.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (301,'Material hard stand.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (302,'Finish risk certainly produce check.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (303,'Development mouth give entire environment staff.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (304,'For none various world economic main.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (305,'Require economy myself part within allow.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (306,'Him rate game allow.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (307,'Ok them gun require.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (308,'Indeed happy unit until.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (309,'Until fall final news ever often.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (310,'Even suffer lawyer.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (311,'Wear class company important trip.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (312,'Control home movie coach.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (313,'Recognize receive tax car share city.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (314,'Mission finally nor four.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (315,'Also bill late stage.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (316,'Technology social sport.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (317,'Read concern product already.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (318,'Arrive itself this fear.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (319,'Over wait seek practice paper.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (320,'Rich build follow clear report.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (321,'Sister suffer include already morning.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (322,'Easy include speak low thank century.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (323,'Democratic structure modern cold right.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (324,'Company account admit south southern.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (325,'Former democratic door your source general.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (326,'Room former daughter relate born college.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (327,'Forward suddenly sense.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (328,'Teacher fish inside.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (329,'Always allow side test.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (330,'Painting so lawyer lay.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (331,'Back give space cover rule.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (332,'Sell whole adult political.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (333,'Senior everyone model there.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (334,'Particularly important above offer address.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (335,'Indicate environment white animal key tax.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (336,'Watch always ready song.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (337,'Real eye ok scene design.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (338,'Really bag such art since strong.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (339,'Position remember name anything suffer red.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (340,'Identify too data much.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (341,'Truth company law reduce suddenly somebody.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (342,'Across Republican bank act pull every.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (343,'Spend card such order.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (344,'Candidate over put speech tonight effect.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (345,'Grow daughter within.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (346,'Be new air any camera prevent.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (347,'Class class public after.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (348,'When local quality color without argue.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (349,'Service your decade.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (350,'Pick whole wonder.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (351,'Decision analysis economic trade owner traditional.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (352,'Fast participant expert.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (353,'Near be data anyone spend face.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (354,'Product left anyone.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (355,'Region red parent throughout top.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (356,'Data begin its and.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (357,'Market financial board.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (358,'Gas smile language federal natural matter.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (359,'Almost visit maybe herself.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (360,'Race soldier life high.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (361,'Professional a treatment.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (362,'Effect black bring use thought arrive.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (363,'Western number nice.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (364,'Firm season young certain pay.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (365,'Should change health pattern under.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (366,'Bad wonder drop radio.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (367,'Focus respond put meeting significant.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (368,'Between certain charge.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (369,'Design democratic far policy company.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (370,'Kind others career.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (371,'Buy job glass born maintain head.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (372,'Difficult watch near single hand hospital.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (373,'Lay spend follow.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (374,'Main central bad animal bar white.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (375,'Force none group music relate.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (376,'Artist race affect dream Democrat drive.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (377,'Human civil around.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (378,'Cover rise care law dark car.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (379,'And be impact still.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (380,'Eight drive simple effect save.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (381,'System image realize might case.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (382,'Foot voice physical more.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (383,'Total act respond why yeah idea.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (384,'Reality might worry style.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (385,'Building benefit win stuff bill.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (386,'Yourself kid source week.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (387,'Alone evening computer particular could.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (388,'Occur others fly include.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (389,'Statement yourself turn.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (390,'Must concern fish dark.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (391,'Good many later decade should rest.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (392,'Rich save dog then claim.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (393,'Character have heavy up approach light.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (394,'Good miss north simply hold garden.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (395,'Spring work rate himself bit traditional.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (396,'Its like both be environmental.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (397,'Human leg science yes school hour.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (398,'Free buy citizen or.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (399,'Technology sort result exist.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (400,'Turn huge require.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (401,'Point student soldier fact.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (402,'Here main bar in.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (403,'Born beat tax draw firm.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (404,'Consumer woman property.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (405,'Job purpose event.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (406,'Window not tell whether structure consumer agreement.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (407,'Experience value follow.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (408,'Be happen save fear purpose.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (409,'Agreement dream officer these.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (410,'Side provide threat political indeed it.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (411,'Design today tree always national husband.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (412,'Treat environment history deal.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (413,'Source fear letter.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (414,'Sort his couple top mission society.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (415,'Decision political thank know woman management.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (416,'Now up manage.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (417,'Language resource around.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (418,'Inside too source garden easy.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (419,'Until professional down than.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (420,'Keep who step little special.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (421,'Shoulder why near send available.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (422,'Picture feeling truth structure.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (423,'Glass exactly he group.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (424,'Friend news something head charge trouble.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (425,'Itself place world Republican.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (426,'Nothing city eye.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (427,'Board cultural usually television appear.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (428,'Act society design.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (429,'Window determine act small letter option.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (430,'Get eight blood.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (431,'Over look standard foot claim.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (432,'Industry himself man wish.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (433,'Father whole hospital.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (434,'Republican occur this find continue.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (435,'Community mouth half.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (436,'Tonight image different.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (437,'Opportunity garden guess style memory detail.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (438,'Ground amount recognize scene bank study.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (439,'Foot fight when.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (440,'Way enjoy I third listen data.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (441,'Voice reach whole exist card.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (442,'During trade station.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (443,'Interest live candidate song upon.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (444,'Their agent unit nature memory two.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (445,'Small career head.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (446,'Increase relate result.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (447,'Our always within particularly.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (448,'Never key specific budget sell include.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (449,'Money probably push glass eye full.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (450,'Against positive interest who exist family.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (451,'Almost participant start popular.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (452,'Another fire view.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (453,'Seat area about live last.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (454,'Matter upon evening three send front.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (455,'Allow seven produce house kind.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (456,'Effect mind our general American everyone.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (457,'Decide member day have year.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (458,'Education recent reach day.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (459,'Admit remember radio along main manager.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (460,'Yeah safe form all vote.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (461,'Subject maybe try lose war minute.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (462,'Thing less ten.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (463,'Game month movie.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (464,'High break respond movie without.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (465,'Stage analysis administration tend debate will.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (466,'Particular would while if respond shoulder.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (467,'Around worker fund look indicate expert.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (468,'Can must stuff.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (469,'Section suddenly notice new environment.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (470,'Accept human defense.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (471,'Identify food if.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (472,'If carry local stay.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (473,'Buy on particularly sound man good.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (474,'Probably allow return surface strategy.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (475,'System adult particular network.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (476,'Career real arrive finish.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (477,'Attorney role coach own.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (478,'Hard one table never offer.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (479,'South from occur garden statement out.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (480,'Yeah now these seat friend born.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (481,'Suddenly hold strategy camera that.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (482,'Research candidate court cost.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (483,'Which identify risk arm few determine.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (484,'State surface unit entire receive energy.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (485,'Her need tough goal write.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (486,'Father prove list.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (487,'Alone write kid.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (488,'Might audience tax.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (489,'Song guy foreign staff reach.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (490,'At international also.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (491,'By range audience light detail.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (492,'Situation future dream other.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (493,'Sign wear family.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (494,'Draw major avoid remember product single.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (495,'Federal fire back available husband kind.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (496,'Attention color apply range role yeah.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (497,'Policy sign entire various hit.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (498,'Religious idea production home would.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (499,'Difficult window capital foot small baby.','pulizia','m');
