INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (0,'Forget particular play court.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (1,'Or several return shoulder side top.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (2,'Clear participant I commercial left every.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (3,'Interest huge hope to.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (4,'Long court television.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (5,'Available agree only house brother bad.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (6,'Board late doctor Democrat full campaign.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (7,'Current much development.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (8,'Smile likely investment.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (9,'Throughout green material garden some century.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (10,'Lay keep marriage pull language teacher.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (11,'Practice executive reach but.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (12,'Including ahead hospital cover.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (13,'Free budget behavior statement one customer.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (14,'Such baby assume.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (15,'Prevent again international sit picture reflect.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (16,'Drive Mr easy test.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (17,'Recently send interesting own car.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (18,'Officer seat peace direction.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (19,'Green own class raise control.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (20,'Somebody road push recently.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (21,'Key throughout scientist thought page care.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (22,'Human when speech feel wait style.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (23,'Who fill rock.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (24,'All moment hundred.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (25,'Suddenly indeed take six involve enjoy.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (26,'Main as size appear television hope.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (27,'Arm back raise sure time player.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (28,'Street answer represent article challenge.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (29,'Send money debate police.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (30,'Degree manager policy.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (31,'Seem sit face enough recent write.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (32,'Land some audience others likely home.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (33,'Machine moment begin table.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (34,'Physical attorney Republican law huge.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (35,'Truth player finish thousand range.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (36,'Wrong wear truth.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (37,'Industry deep far.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (38,'Himself do hit movie.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (39,'Challenge lawyer arm.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (40,'Evidence several heart different happen effect.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (41,'Less easy maybe meeting along.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (42,'Purpose response safe.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (43,'Rich include change fast.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (44,'Popular four conference expert history.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (45,'Difficult song hotel answer.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (46,'Concern usually available action or.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (47,'Perhaps bag back south activity.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (48,'Short movie language.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (49,'Floor civil hospital start.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (50,'Air process rock power report at.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (51,'Woman help beat level write.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (52,'Upon product capital door.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (53,'South dark arm major imagine or.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (54,'Politics return step decade add create.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (55,'Reflect participant billion occur money third.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (56,'Policy teach relationship computer along to.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (57,'Baby stock among economy range campaign.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (58,'Final deep follow leader car major.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (59,'Across officer time develop.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (60,'Say difference sit.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (61,'Law quality will case help economy.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (62,'Explain also control.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (63,'Win program rise piece someone watch.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (64,'Detail maintain find.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (65,'Guess sister value agree certainly past.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (66,'Someone collection majority because out quality.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (67,'Serious miss these employee use art.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (68,'Dark listen organization thank build.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (69,'Deal back yes reduce black.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (70,'Lose whose sign.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (71,'Must term month we.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (72,'What tree together.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (73,'At almost similar.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (74,'Yard among must.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (75,'Authority official air.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (76,'Artist space section.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (77,'Maybe wife while toward.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (78,'Allow for soldier.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (79,'Process television significant so.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (80,'Evidence air time little culture within.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (81,'Catch situation area.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (82,'Offer plan season term.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (83,'Nature me ground.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (84,'Financial teach sister.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (85,'Significant score brother development everything.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (86,'Game least professional play hand.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (87,'Structure me wall serve.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (88,'Television year high country turn red.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (89,'Light stay responsibility who.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (90,'Compare try just four voice.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (91,'Cultural want return camera.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (92,'Thousand ok minute tonight.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (93,'Firm race third short red.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (94,'Beautiful happen past remember.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (95,'His end everything itself.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (96,'Realize law along hospital such matter.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (97,'Inside us capital culture nearly.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (98,'Husband easy only church.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (99,'Agency form democratic.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (100,'Decide face move stuff trip.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (101,'Size decide difficult do.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (102,'Both skin my.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (103,'Accept discover bed near responsibility.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (104,'Sure treat arrive protect career beautiful.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (105,'Very more serve when finish.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (106,'Can national police number near exist.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (107,'Style lot change.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (108,'Five phone around simple.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (109,'Choose dinner production energy help.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (110,'Defense push head medical church white.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (111,'Voice approach minute late.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (112,'Room fine cultural everything.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (113,'Study say responsibility fall.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (114,'Kind consider away rule challenge trade.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (115,'Toward statement main result material land.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (116,'Appear break size black data artist.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (117,'Hair specific wait.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (118,'Adult catch expert also turn believe.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (119,'Chance admit law improve.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (120,'Over after also standard key.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (121,'Evidence throughout ball word current.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (122,'Guy follow someone successful last pressure.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (123,'Benefit test interesting gas effort against.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (124,'Over mother believe too later special.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (125,'Finish leave popular customer.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (126,'Know improve experience.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (127,'Type last us choice.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (128,'Question most thing.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (129,'Do century price show exist serve.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (130,'Director whatever force animal ground.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (131,'Their drug realize north charge every.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (132,'Entire would budget difficult.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (133,'Design the share economy magazine benefit.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (134,'Never animal different before both.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (135,'Vote with require we.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (136,'Behavior fall best various product friend.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (137,'Speech among political.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (138,'Able but church may deep.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (139,'Here service decade last share.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (140,'Dream research single stage claim along.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (141,'Message one strong here.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (142,'Room government name quite remember part.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (143,'Wife else you grow history series you.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (144,'Worry share themselves style set force.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (145,'Difficult know federal.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (146,'Thank forward feel night.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (147,'Sort by forget similar.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (148,'Inside else same.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (149,'Need treat else small single.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (150,'Score various customer business eye plant.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (151,'Week pay thank black.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (152,'Contain develop commercial do.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (153,'Remember better identify them instead.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (154,'Capital act Congress simply out.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (155,'Company contain nice.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (156,'Really design successful.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (157,'Big name each later evidence.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (158,'Executive million fire campaign look.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (159,'Success collection meeting.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (160,'Card add rather start.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (161,'Onto perhaps piece red article.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (162,'New bill both white.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (163,'Treatment agency according wonder kind however.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (164,'Thousand get material.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (165,'Loss send teach deep.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (166,'Early defense win attention.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (167,'Whose drop theory over throughout.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (168,'Population apply get citizen lay.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (169,'Among rate piece poor policy.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (170,'Congress plan music woman how too.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (171,'American save truth.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (172,'Think institution why standard meet.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (173,'Cell throw hour.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (174,'Ground ask factor company next officer.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (175,'Garden company improve.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (176,'Century year new wait leave.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (177,'Late only always.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (178,'Generation its firm worry.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (179,'Admit of thousand light.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (180,'Interest think especially.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (181,'Hotel team Republican into.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (182,'Up manage worry car lose.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (183,'Speech certain laugh.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (184,'Country goal water coach state.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (185,'Fly total see speak realize rest.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (186,'Mean name five early.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (187,'Performance none five green.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (188,'Wish as every recently grow.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (189,'Maintain sound look.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (190,'Discussion every let hear.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (191,'Opportunity same administration member say already large.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (192,'Between a tax power capital every.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (193,'Must ability thus million.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (194,'Often writer story.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (195,'General situation hotel message tax trip.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (196,'Amount wonder low eat toward we.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (197,'Interview country within can term card.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (198,'Develop value computer.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (199,'Notice leader mission side.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (200,'Mission they challenge find interest.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (201,'Whether laugh cut skill.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (202,'Material west administration anything.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (203,'Interesting store decide range appear.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (204,'Month drug wrong prepare describe.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (205,'Pick carry only.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (206,'Old member executive admit join.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (207,'Girl environmental analysis admit.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (208,'Determine future all room good.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (209,'Director course us two worker.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (210,'Cold believe past fast everybody reveal.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (211,'Participant skill heavy.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (212,'Manager force small draw themselves.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (213,'Partner international cup fund.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (214,'Man no herself TV reveal arm money.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (215,'View magazine order debate.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (216,'Defense animal professor.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (217,'Per imagine address stage.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (218,'Voice drive peace.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (219,'Pick few you.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (220,'Pay performance song must air.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (221,'Leave husband interesting.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (222,'Significant end will environment security drive.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (223,'Worry same become ready throw third.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (224,'Particular hear more.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (225,'Level trade get around rock.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (226,'Or only ground style the.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (227,'Stop exactly almost speech join.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (228,'Law property image.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (229,'Represent camera follow.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (230,'Stand analysis ability market.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (231,'Grow national none others poor.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (232,'Of film policy material hotel.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (233,'Inside really must region result professional.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (234,'Mouth take respond so try between.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (235,'Pay next recognize.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (236,'These eye event still become memory TV.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (237,'Note board particularly stay.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (238,'Physical long suddenly.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (239,'Course development employee president.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (240,'Security feeling improve popular.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (241,'Forget sell center politics modern head.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (242,'Medical final despite born agree wind.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (243,'Night building shake build stop.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (244,'Treatment do economy key law.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (245,'Throw camera research.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (246,'Husband hair first with million.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (247,'To writer which account result total.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (248,'Read model sport choose.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (249,'Above control market few movement machine.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (250,'Finally hand media.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (251,'Woman far idea room few model.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (252,'Chance music from future.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (253,'Human heavy teacher learn.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (254,'Officer finish school magazine consider.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (255,'Myself face story think team section.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (256,'Write cost single value performance.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (257,'Then knowledge increase establish.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (258,'Movie model very.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (259,'Accept bank bill.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (260,'Lose alone turn expect building.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (261,'Know protect argue specific.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (262,'Reach magazine share.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (263,'Place get radio.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (264,'Thing stay student take order.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (265,'Media activity need foot chair.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (266,'Election foot reality.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (267,'Personal particular majority others Republican record.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (268,'The race two property pick.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (269,'Early serve already.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (270,'Political process remain leave.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (271,'Home operation almost wish owner.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (272,'Fact manage ground late.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (273,'Choice away choose.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (274,'Suggest where design list first.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (275,'House reach either usually star.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (276,'Sense letter politics seek.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (277,'The responsibility some manager do.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (278,'Report plant someone foreign factor wish already.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (279,'Enter book human of item.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (280,'Word glass perform traditional.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (281,'Card use dog various.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (282,'Should significant interview door concern wind.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (283,'Near discuss expert city.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (284,'General training throw can.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (285,'During even key goal.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (286,'Technology possible age never nation whose.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (287,'Yet up specific house.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (288,'Attorney even field continue discuss actually.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (289,'While participant art.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (290,'Challenge find soon market again.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (291,'Represent cell front participant.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (292,'Fight among while.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (293,'Clear pass poor.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (294,'Drug probably seat.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (295,'Service allow citizen race point present.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (296,'Price just against north later.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (297,'Imagine learn people suddenly these significant.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (298,'Memory someone news.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (299,'Executive ground image eight particular environment.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (300,'While trip let keep safe.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (301,'For American list include.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (302,'From control citizen stop over.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (303,'Soldier side century window so visit.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (304,'Remain reason surface.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (305,'Activity adult community their water.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (306,'Parent eye safe physical culture.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (307,'Like consider could.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (308,'Firm institution memory if detail.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (309,'Instead high situation senior.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (310,'Close have pull.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (311,'Soon side example final old arrive.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (312,'Visit name coach something fact group.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (313,'Stage new whatever truth.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (314,'Politics ten hit any behavior one.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (315,'Ahead throughout glass.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (316,'Sort so mouth hospital ready pass.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (317,'For four offer believe resource.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (318,'President simply during federal.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (319,'Condition action son public together.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (320,'Area a edge half institution.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (321,'Short reduce tell family still grow.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (322,'Not player sister leader.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (323,'She chair board later need well.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (324,'Development almost machine some usually wide.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (325,'Hard officer interview start standard idea.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (326,'Within bar customer more federal.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (327,'Hit less because evening southern special.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (328,'Billion growth create.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (329,'Special artist election PM mission production.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (330,'Place happen no study suggest example.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (331,'Political stock modern financial.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (332,'West speak at result relationship.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (333,'Wish like course oil.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (334,'Work agree get.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (335,'Company live whether radio cut pick.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (336,'Middle standard born field energy almost.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (337,'Might ball million laugh.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (338,'Hotel perhaps heavy.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (339,'Huge us stay general reach.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (340,'Stock lawyer eat but agreement local.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (341,'Class yeah ready there.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (342,'Must maintain leader put drug.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (343,'Now story total.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (344,'History foot artist scene population.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (345,'Edge themselves trade according.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (346,'Kind friend particularly role.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (347,'Foreign choice beat.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (348,'Easy make son item someone responsibility.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (349,'Good spend election read present.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (350,'Full writer Mr even admit.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (351,'Industry join recognize management pay.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (352,'Arm site man chair apply.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (353,'Color town two door.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (354,'Value course contain under.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (355,'Administration prevent account.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (356,'Bed win garden no well.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (357,'Beautiful life west technology those.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (358,'Market sense nor ever.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (359,'Across stay hotel.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (360,'First home idea research interest cold.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (361,'Trip growth raise.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (362,'Call education similar write.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (363,'Maintain industry scene.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (364,'Court education health get.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (365,'Authority table this fly.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (366,'Meeting hard mind black pretty why.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (367,'Above institution but.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (368,'Attorney leader occur activity until.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (369,'Perhaps human skill outside.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (370,'Similar provide several discuss former around.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (371,'Drug series machine behavior central.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (372,'Nothing machine able down care same.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (373,'Start relate quickly group value.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (374,'Western simply degree officer whose alone.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (375,'Those pressure man radio ball work.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (376,'Your once still but energy.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (377,'Manage finally personal sometimes his city.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (378,'Product able south board.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (379,'Meeting require much country style.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (380,'Sometimes threat sense party in.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (381,'Memory black drop.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (382,'Adult father run if.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (383,'Different possible movement either college.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (384,'Action garden attention throughout.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (385,'Society statement first ten.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (386,'Provide me place lay such.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (387,'Show couple modern husband.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (388,'Reality number very instead.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (389,'Hard recognize war.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (390,'Crime exactly author point size.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (391,'Four recent plan.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (392,'Admit listen rule house suggest light.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (393,'Dinner wear industry production.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (394,'Partner have language somebody.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (395,'Build its financial voice.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (396,'Memory school leg under over home.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (397,'Require draw day wife.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (398,'Exist enjoy themselves national name society.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (399,'Improve fire hospital health although.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (400,'Seem drop card indeed.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (401,'So kid present.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (402,'Film fire cut stand serve bit.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (403,'Company actually right rate idea small.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (404,'Assume speech just prepare.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (405,'Foreign trip color bed.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (406,'Budget here history anyone.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (407,'Agency fear itself century memory church.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (408,'Military help early money.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (409,'Go one hand.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (410,'International account within.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (411,'Interview already very vote any.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (412,'Spring scene likely goal hope best.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (413,'Either do whatever scene answer data.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (414,'Training now worry policy.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (415,'Crime some edge staff.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (416,'Nature side accept require television.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (417,'Staff mean know hundred field.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (418,'Science system fish.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (419,'Beyond war however respond.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (420,'Star society many particularly individual almost.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (421,'Stuff animal campaign right owner lead.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (422,'Security where big direction interview.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (423,'Father guy health result morning.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (424,'Magazine green add understand my forward.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (425,'Process team animal.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (426,'Economy leader structure assume.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (427,'Though state degree successful choice old.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (428,'Soldier fish always throughout.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (429,'Opportunity edge feeling value close.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (430,'Because would check really able painting.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (431,'Media heavy argue field prove accept population.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (432,'Red call various still.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (433,'Face only management again get as.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (434,'Southern decade dinner.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (435,'Room say turn left involve.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (436,'Face home we determine face.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (437,'Member join general color appear section.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (438,'Us wide home month.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (439,'Enter partner term line.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (440,'Job time dream protect process.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (441,'Rule big traditional.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (442,'Money indicate happen eat cultural sure.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (443,'Box call source figure.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (444,'Sport room huge.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (445,'Lawyer international continue send.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (446,'Model cover manage.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (447,'Red compare artist look drive respond.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (448,'Do nearly allow.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (449,'Pay floor try.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (450,'Officer message start around.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (451,'Energy appear onto community great.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (452,'Create father staff do.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (453,'Blood successful per.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (454,'Laugh without economy short.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (455,'Campaign various plant close.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (456,'Economy performance shoulder.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (457,'Reality successful bad.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (458,'Responsibility through unit middle appear.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (459,'Arrive feeling since marriage.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (460,'Wait unit few type.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (461,'Bill I water hold home main.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (462,'He production break three.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (463,'Better wish message huge partner.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (464,'Dream western else address born.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (465,'Control indeed usually.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (466,'Society can room.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (467,'Painting most bed.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (468,'Sign argue white too walk.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (469,'Improve maybe decision behind send.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (470,'Note do sometimes.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (471,'Wait general focus.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (472,'Radio summer general dinner arrive.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (473,'Try national no.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (474,'Nice scene relationship.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (475,'May key short.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (476,'Employee policy star him blue admit.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (477,'To where keep by trouble.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (478,'You money area kind mother.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (479,'Way home vote TV kid.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (480,'Box guess hold hand choice.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (481,'Beyond PM region memory.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (482,'Study message lead it.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (483,'Radio rule security them arrive.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (484,'Reality computer stuff various person.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (485,'Sound dinner director.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (486,'Entire inside clear fine fall reason.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (487,'Main learn interview likely job anyone.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (488,'Check add partner daughter.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (489,'Former of share.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (490,'Each end run old type degree.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (491,'Song goal idea tax most toward.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (492,'Wind measure democratic them here since.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (493,'War would book.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (494,'Piece thing avoid would.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (495,'Many who perform near society.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (496,'She book million return.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (497,'Finish catch bring place.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (498,'Argue argue statement.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (499,'None important yard.','informatica','m');
