INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WYYATV','Pm brother security cup.','DTDOOJ22Z06K945C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DCPDYM','Event by put only together.','EQYTBA31Q09Q200J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AGZAWF','Military work anyone.','QBYOOQ08X74R162F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VQXTSZ','Arrive occur safe season increase throughout.','CWVLQR58X11P667B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('YILJBA','Southern one both special on national.','XDCUFR30D05X629K');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AOBLSX','Nature treat seek.','OBBWCA63E44Y013G');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CODMLY','Tell pass movie any hotel.','TFRNSQ83E39L878Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('TROCQE','Stock official name book free operation.','AQATPV50H98J205V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JHOWUO','Office movement recently.','GIMRCA19D78U533Q');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JXTRPE','Product pretty box offer different practice.','DLLFMH91S38Q894Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NTVVFI','Hot data western first.','VJXSJB30Y12R515O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('UUAEIR','Administration have position.','AKNURX41K41J713M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('HHVUJK','Officer admit down memory evidence.','SNWCOS97Z47L564O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CVVQPQ','Low address information then business.','XSLQVX00S88I376Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('LCTMBN','Material could determine them realize degree.','BIPHMJ54H03M158E');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OQMRZK','Model society war.','UQDOYD77K79C328D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SIGQIZ','Wall we reason.','GAVGAR49L81K552Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ADRIEH','Hear can then exist most.','PJUYWS52A14R990N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('UPJWRL','Dark threat hold on book face.','MNZQKP15A74Z429G');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FUBTLV','Candidate off traditional.','ECEUTB06H00H342A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NWAZVB','Herself herself away significant soon serious.','JPBBFO74I21O460E');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PCJNDC','On answer official your note audience.','LPUQKI39V92C908J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('LOFFKH','Program fact consider this successful.','SOYUKS97Q27E243T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RYWDPZ','Direction than school indicate week.','VAKHDJ31L00X070C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RPHHXX','Young spring building personal watch.','FQJXXI54Z09S126P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XXDAAM','Call travel discussion director best stop.','DTDOOJ22Z06K945C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XTPSYM','Financial art scientist follow education.','EQYTBA31Q09Q200J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QTWQGD','Scientist project range against.','QBYOOQ08X74R162F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OFDGCG','Agency himself customer put.','CWVLQR58X11P667B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XDFGAJ','Everybody want participant several TV officer.','XDCUFR30D05X629K');
