INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZXTSNW','Plan usually reveal here world again.','QRBNMJ16D96I872J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WPIUQD','Pattern could raise avoid.','RIVGIU83X57C349W');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('THQQYK','Teach water choice town old.','QMMRCJ24S36B156A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DZACOM','Prove site best.','QTCCBZ24J03T465M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ACQYMC','Consumer range even.','JHZVXD87A63O884F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PUYFXH','Effort soon reason media.','MVQZUK39B24R107Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DAYVCC','Easy remain size team expect.','SVQJYE36N92S497Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DYQSNJ','When plan always drop.','HKNZRY23J49B386P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('GEIBOC','Me buy shake husband usually this.','HKCUKW15S63F781B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OFJLRK','Drug edge ever someone create question.','RZPXYK65Y55Y929A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WLHYFV','Water court in guess participant child.','DYJOND77R02F176P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('KRZFBR','Conference morning thank.','UGAHVC93J44E595R');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZRFTES','Bill charge nearly wonder part.','CXUMSF79H35N333Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('KYUZHU','So paper once Mrs.','BUFOME92E53X901P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('UCLUSS','Many understand to.','VUXZVW64W96K215N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('KZIRMD','Decide performance physical.','ROZIII48G92X341S');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XTPUSR','Economy unit usually into about coach.','OCIXPI70H91T157Q');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CXJRRV','Political allow author one serious.','OFKJNN67W14T786Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('IOYQJD','Pm skill much new media eight.','VCQLXR82X01N304Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('GPFUQQ','As father test play apply.','YQTGOJ28C06G933C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XMSDAA','Think stock improve.','XBSHME28V54Z741O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OSCZSR','Talk drive Congress.','ORRHFV51P14J889B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RBLVUL','Another late attack suggest Congress.','LXYBOO64H88U500L');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JOBDDL','Course year statement buy story mean.','IGQNSM82D00T556J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OZYRAN','System development since international term.','HFVDLB65N35K890F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('LKAQLG','Stop itself attack necessary after important.','QRBNMJ16D96I872J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('GXNGGJ','Name them wear.','RIVGIU83X57C349W');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MEOBEI','Husband for result difference.','QMMRCJ24S36B156A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('HGQNJW','Enough debate six young decision voice.','QTCCBZ24J03T465M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WLIQJC','Listen writer investment exist.','JHZVXD87A63O884F');
