INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('GREDZT','Create base cell.','TZOXVT22D60A966W');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('HWDGON','Factor nor fast campaign city page.','MQJSFE21Z34X735D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WYWFMD','Special would themselves firm.','XIXVKC16F73T903A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('EPIEBQ','Painting lot safe worry control.','RRSVDA36B22H935I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RYWXXH','Dream even bag help why together.','DJLZUW59Y71G953C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DBCYIS','Lead radio value deal.','YLCMRU71V53J236X');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XLEOOK','Cause family instead prevent account.','MTWSGG55M84O417C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ETTGPW','Will conference especially same.','PDUKUX94J41H741D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OFYKSC','Usually without affect.','SOMWBA91R37V999Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VMEJTA','Fine receive man.','HNEUEW42E65J080N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FKNWFK','Race wall much.','BPOSKQ47M59B753D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OVDTJX','Certainly listen last address understand.','JGZLYH35K81B044Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OWNGOQ','Man management little young economic.','ZMYAQD53G28P137O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('YLPJDK','Factor everyone work one few film.','JPRODO56C10H452X');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MYYWUG','Team social protect.','IHYMVC62N13R747C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OUTANM','Room whom civil side defense speech.','ABWMOW99S91H597H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OWVPVQ','Decision win kind end military.','LNYNFZ10D89W214R');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CESTWP','Baby suddenly simple.','INOWCP20K93D374X');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WGGXRN','Life team interest analysis use.','IRCWNR84K04P662B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('IACDVC','Treat soon can wide.','XQYMQN12O46N657V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('LXMNNG','Attorney early theory.','ENTZZY93F43C721L');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NBYWYV','Media two listen commercial pay society.','CVKMPV71C17V421B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QOAEQA','Music this wife year.','UZJAIN36R56C145S');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('BAZHRW','Level son him movement.','COVIPS64X48H573V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VBVDDQ','Main activity first leg become.','SWNYUZ40K29D864P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AAYJCP','Fact standard hear only none.','TZOXVT22D60A966W');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('EMZQFQ','Anything available good.','MQJSFE21Z34X735D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QHJLQU','Tend maybe mother our.','XIXVKC16F73T903A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CXWONO','Reveal than reflect every special.','RRSVDA36B22H935I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FMVWWY','Market avoid over authority perform.','DJLZUW59Y71G953C');
