INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RWPUXE61K17N816U','Andrew','Knight','1986-11-05','South Thomas');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DTQCKL57K18N088Q','Alyssa','York','1992-08-26','Vegatown');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GMOAJC47X16I519D','Jorge','Trujillo','1974-12-09','West Brianborough');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VXPWVB69V62N314T','Clayton','Gray','1976-02-02','Charlesville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OTBGJT48G74N996C','Michelle','Foster','1977-02-06','Port Stephanieview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UECBIP85M44C676H','Paula','Blankenship','1980-10-10','New Jamesfurt');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AJCOBH93M21M456G','David','Little','1961-09-26','West Heatherfurt');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WJIXCT30A50D629L','Robert','Morris','1966-04-02','Dianamouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LDFNPE18G14H081J','Joshua','Lee','1995-11-08','Clarkstad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VUXVGR69O97C127Y','Chad','Sexton','1970-10-29','North Caitlin');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KTFRZL52O78M837M','Bryan','Anderson','1988-01-12','Kingville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EEZSEV97F38E929Z','Robert','Hammond','1957-05-20','Scottmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UHPHQE94J86F132U','Kayla','Rodriguez','1973-08-02','Kylemouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AAEDSO31Y89M080O','Justin','Rangel','1953-08-07','South David');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GELKRO02I45V634H','Crystal','Meyer','1968-09-19','Jimmyville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YNGLQB71X16D064P','Victor','Bates','1962-03-29','Port Lisaview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AWZNKH21K78J076R','Richard','Ball','1952-09-07','Novakbury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XGAYVQ03W37J087B','Olivia','Beck','1957-12-09','West Kenneth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BHDUNJ17Y33P916P','Jennifer','Thomas','1978-09-28','Derrickville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EAHWYK66R00V022D','Albert','Barnett','1984-08-10','East Christina');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HTGSDF01F15T834P','Caroline','Rowe','1957-09-16','Brianfort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TCWRGZ29M34F997G','Debbie','Castro','1970-06-27','Heatherport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PPMCNU84U52L662O','Victoria','Hall','1956-02-08','New Seanhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RDLTOT28M12C579H','Kenneth','Lopez','1981-05-22','Lake Casey');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WZRIUC59M44E944U','Robert','Bowen','1974-02-11','Jenniferbury');
