INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PITKQZ80F13R759Q','Eric','Martinez','1984-09-23','Randyfort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LHVIKO67T27X732W','Garrett','Flores','1996-11-09','Donaldmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LLMWOJ16M24K223D','Erica','Johnson','1958-10-08','East Wesley');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BJFTYD34O56H217C','Jim','Gordon','1976-12-03','Fitzgeraldshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VCSDDB68D23D607G','Darren','Kim','1992-03-15','Coxmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YOWCMA38F78O198N','Stephen','House','1952-01-14','East Sheliaberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HVMOAD77R94J399S','Joel','Gordon','1980-11-26','Stoneburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JBSAPC43E04T308Q','Craig','Ochoa','1994-10-31','Juanburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BKNPNZ94U95C461U','Mark','Crawford','1992-05-06','Clarkside');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QXGJCQ71R20G981L','Brandon','Rodriguez','1989-03-21','Karenfort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AZQCYD57M00B858J','Patrick','Smith','1989-02-01','Woodwardstad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MCRMTM18B77G773H','Julia','Zamora','1984-02-24','Danielhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KODHIA02A97C912Z','Jillian','Jackson','1981-08-17','South Danaside');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XLFUSE66D85I399M','Joseph','Gay','1997-08-28','Stoneshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QEJERU76C39W148B','Sharon','Potter','1977-03-10','Courtneyhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ETOJLI80F28I374S','Timothy','Parker','1996-12-05','Ramirezview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KCDYOS17W67D780N','Raymond','Nunez','1967-03-10','West Gregory');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KNGZDQ79E72X557P','Sean','Reid','1959-10-21','Ramirezbury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YFIXDZ85Y42L192J','Christopher','Haney','1974-11-10','Shawmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VMMEZS23G61J435G','Karen','Vaughn','1987-06-12','East Amandaberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IYZYCE35D39K686T','Sara','King','1998-08-09','New Victoria');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZBKHFB95A10D247T','Shawna','Harris','1986-11-08','New Tyler');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BLBIWD01B61N227T','Stephanie','Hampton','1963-11-13','Durhamville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GVIPLE06H50C846P','Caitlin','Nixon','1957-10-02','New Jamiemouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UWJHGN86D95I238Y','Amber','Ayers','1984-10-18','Christianfort');
