INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NXQMAR68N68Z266T','Martin','Fowler','1976-03-19','East Gregoryview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZRPAYY28F67L265D','John','Hall','1991-12-20','Smithmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FRALJH64D41C479G','Wayne','Moore','1977-04-23','Danielmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PPHPCY80G87Q823Q','Pamela','Mosley','1957-11-07','Martinezhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BVPIPT02C24B174A','Kimberly','Gilbert','1955-11-16','Landryport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MILCJE31Z45J266V','Suzanne','Park','1995-09-27','Benjaminmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QSGGWN97B72M003J','Kimberly','Brown','1953-06-23','New Aimeeburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YHUMGV39D21X031S','Maxwell','Santiago','1960-06-25','Harrisport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YUUYSR46B75G502B','Paula','Holloway','1955-05-17','South Kristen');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JFQQWM59B09S968F','Amy','Hall','1999-02-02','Gilberttown');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UIVISF05S53U204P','Sean','Osborn','1964-07-21','Port Zacharychester');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZGXVWQ59U96O985E','Krista','Davis','2000-01-19','West Sonyafort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NRJHSU41Y83A995Y','Jessica','Gardner','1960-06-14','South Becky');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RKPBUU35C39Q674T','Crystal','Gonzalez','1978-04-01','Pattersonberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NGLIDQ01G68M169F','Timothy','Norris','1979-01-19','Matthewport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KLKYDT57J56B937R','Sarah','Ibarra','1958-12-26','Gregoryport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VIATOJ46P12J089Z','Amanda','Thomas','1960-10-18','New Margaretshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GPIMUT72O92M137F','Jeffery','Hardin','1991-04-01','Bakerton');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CQFOJV94J35S426F','Justin','King','1998-07-14','Lake Bradley');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GIKCDQ14V13X571Q','Michelle','Weaver','1983-07-12','West Larryside');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IVAXBW91W13C250M','Mary','Kelly','1958-12-05','Charlesside');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('SBIUHT05N59G330W','Brandi','Campbell','1984-04-10','Port Alicia');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XIVFIB08V91W080W','Kayla','Tate','1967-03-05','West Keithshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GGGNRU44D19Q243C','Kelly','Powell','1986-09-09','East Jamiefurt');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TIXZBT63B82Z761I','Catherine','Cox','1973-06-07','South Crystal');
