INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (1,'Forget upon look.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (2,'I necessary management network what.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (3,'Thought art purpose tree least bed.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (4,'Although Congress term.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (5,'Few treatment performance.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (6,'Nearly fact skin.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (7,'Poor who trial population impact.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (8,'Kind turn respond democratic gas.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (9,'Result or they line serious.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (10,'Final same media song offer nation.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (11,'Part claim might nearly past young.','mobilia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (12,'Tell end agreement nearly.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (13,'Present must impact budget room nice impact.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (14,'Century wife couple allow arrive owner.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (15,'Other fire huge leg.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (16,'Eat end throughout eight.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (17,'End food though pay similar.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (18,'System product century.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (19,'Agent water fact image ready degree.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (20,'Get evening personal final Congress change.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (21,'Nearly field support quality wait everyone.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (22,'Important must memory myself.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (23,'Blue thus exactly rise.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (24,'Garden when happen well.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (25,'End administration animal blue play.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (26,'Leave establish easy meet condition allow.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (27,'How ask movement usually.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (28,'Wish traditional yard near world marriage.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (29,'Some serve generation boy parent unit.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (30,'Sport road anything.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (31,'Court real very.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (32,'Standard page page thing pull.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (33,'Daughter more dark.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (34,'Should hair room that probably teach.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (35,'Box design wife thought.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (36,'Answer exist main into your a.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (37,'Activity station science yes.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (38,'Receive recently entire.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (39,'Across mother animal arm material city.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (40,'Build about civil allow you.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (41,'Single attention enter onto.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (42,'Your attorney daughter work where personal.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (43,'Enter already like final.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (44,'President fund each trial.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (45,'Size less recently safe.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (46,'Case week ask Congress less.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (47,'Effort occur cover impact prevent just.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (48,'Financial present catch rest.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (49,'Move spring kid machine.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (50,'Level right bring music card.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (51,'Bad both peace time to.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (52,'Local message race.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (53,'While surface memory difficult kid but.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (54,'Skill side as art level fine.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (55,'Actually modern yes name serve able.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (56,'Know think teacher especially hit every.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (57,'Few sing I vote.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (58,'May feel maybe those nice.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (59,'Production clear lead usually executive.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (60,'Road rich season hospital.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (61,'Imagine station month speak record.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (62,'Represent decide I skill.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (63,'Rule structure so situation necessary.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (64,'Reduce upon traditional.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (65,'Often bad already newspaper building.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (66,'Woman deal cover time admit.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (67,'Ground present down.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (68,'Statement method without.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (69,'Recent art approach.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (70,'Summer court special until wind.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (71,'Mouth Democrat within we adult modern.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (72,'Still agree phone blue.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (73,'Become do artist.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (74,'Herself or million play effect.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (75,'Various believe hundred.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (76,'Crime wonder whom short forward even.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (77,'Every prove garden sport.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (78,'Price us summer.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (79,'Including improve up evening imagine.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (80,'Deep very program trade up.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (81,'Plant nearly make thing camera.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (82,'Crime cover both.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (83,'Relate consumer during interesting most.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (84,'Central half perhaps appear.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (85,'Experience big box soon base look.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (86,'Determine edge safe new.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (87,'Edge defense along political agent.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (88,'East trade hospital could good.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (89,'Yet impact process them.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (90,'Want friend into.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (91,'Short fine partner.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (92,'Maybe agree certainly drug.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (93,'Might reach everybody boy.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (94,'End any growth.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (95,'Decision necessary can become.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (96,'Miss base administration dog political.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (97,'Technology growth white trade.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (98,'Heart ground sense dream.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (99,'Performance thus that this live.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (100,'Should until their.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (101,'Right leader color follow local point.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (102,'Enjoy would high writer all note.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (103,'Toward low color.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (104,'At indicate record relationship.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (105,'Run week type production.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (106,'Pull save five unit head guess.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (107,'Land subject around.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (108,'Glass size who together.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (109,'Less become sometimes yes hair.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (110,'Response television identify.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (111,'Mention bit those approach should.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (112,'Town step find.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (113,'Instead economic huge can language his.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (114,'Within live term call spring democratic.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (115,'Either body three.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (116,'Become important parent whatever.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (117,'Write most foreign parent white.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (118,'Though spring star one.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (119,'Have decide just sing many.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (120,'Store federal parent western.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (121,'Economy Mrs group.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (122,'Once office land role everything.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (123,'Until ability quite green.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (124,'Someone company world mean window.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (125,'Of tax ago.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (126,'History common good.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (127,'Include scientist door person quickly.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (128,'Husband know land.','elettronica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (129,'Own on trial indeed recognize of.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (130,'Along itself west enjoy produce couple.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (131,'Country surface style.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (132,'Range above recognize senior customer traditional.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (133,'Over method which air next more.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (134,'Throughout bank thought exactly treat.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (135,'Center company fire.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (136,'Difference care project.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (137,'Former finally wall for.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (138,'Baby road pay understand.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (139,'Name data his television consider left.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (140,'Perhaps nothing available.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (141,'Store network not.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (142,'These prevent when hit.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (143,'People sure most effort window.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (144,'Arm available through form bit forward.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (145,'Call allow yeah reach you.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (146,'Though so of idea after dark.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (147,'Person trial with name reflect.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (148,'Fast leader increase.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (149,'Third fly feeling work policy member.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (150,'Grow ever management direction young picture.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (151,'Skin loss which response green goal.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (152,'Religious when despite.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (153,'Single manage leave official beautiful.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (154,'Policy great audience property end.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (155,'Star market citizen.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (156,'Can seven commercial road.','mobilia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (157,'Few research reduce camera those.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (158,'Republican report serve.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (159,'Forget soon eight candidate many top.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (160,'Effect summer through order.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (161,'Teach both hot almost.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (162,'Every whom TV fine sit.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (163,'Official board common piece.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (164,'Each the alone executive.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (165,'Clearly parent data country near.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (166,'Force PM strong.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (167,'Girl meeting clear technology by.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (168,'Animal small network nature senior assume.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (169,'Team step prove suggest turn behavior.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (170,'Business late leg.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (171,'Treat child set.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (172,'Situation board capital important beautiful.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (173,'Most most source other.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (174,'Police imagine TV seven.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (175,'Rate should rich.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (176,'Under politics audience force choose.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (177,'Wear mind public guess kitchen leg.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (178,'Should account from.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (179,'Lawyer discover win.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (180,'Movie see statement.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (181,'Early collection must maintain for.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (182,'Store wind physical rather.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (183,'Among phone form several.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (184,'Natural example arrive fire.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (185,'Body usually recognize determine apply.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (186,'Fund less method doctor.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (187,'Difference day dream industry conference.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (188,'Government right young reach fish stand.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (189,'History participant quickly this director firm.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (190,'Almost visit around.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (191,'Process where seat task.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (192,'Health analysis finally same.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (193,'Its role in gun one common.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (194,'How same woman ago.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (195,'Bar piece create pretty available final.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (196,'Itself leg left if.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (197,'Ahead somebody almost option draw message.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (198,'Two reveal market.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (199,'Them degree it recognize.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (200,'Glass there soon low.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (201,'Claim someone up myself.','mobilia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (202,'Best race theory cold.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (203,'Dream forward fight foreign most.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (204,'Mean strong hit.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (205,'This cup method fire north stage.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (206,'Decade should nation structure decade service.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (207,'Similar idea old.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (208,'Process stay owner.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (209,'During religious day indicate keep policy.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (210,'Even foot service meeting bill.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (211,'Buy keep guess travel believe pressure.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (212,'Network nature recognize do protect can.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (213,'Heart add rule quality ok.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (214,'Important carry usually experience.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (215,'Worry whatever inside few address.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (216,'Protect keep debate have feel.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (217,'Weight game summer west.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (218,'Usually situation all prepare commercial.','libri','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (219,'Data company country charge.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (220,'Throw energy no.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (221,'Kitchen class study must page.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (222,'Help may director why whatever.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (223,'Author follow help product friend team see.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (224,'Get party science.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (225,'Sure executive election stay contain.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (226,'Physical glass past day.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (227,'Field class defense education.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (228,'Such TV stage game half then.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (229,'Edge test practice.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (230,'Sort network board decade.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (231,'Bank minute news.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (232,'Alone rate admit test this thing.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (233,'Success machine something situation.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (234,'Ability hotel son that father test.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (235,'Event specific color heart maybe.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (236,'Particularly majority candidate.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (237,'Hot surface experience receive great religious.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (238,'Central skin down seek.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (239,'Industry of glass general.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (240,'Worker wide window yet send man.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (241,'Piece choice appear.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (242,'Computer few relate.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (243,'Wide national order voice might see.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (244,'Stuff color evening.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (245,'Sport sometimes hospital hear particularly look.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (246,'Ten truth painting serve.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (247,'Avoid into event during party.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (248,'Focus response reflect.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (249,'Very world tree.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (250,'Movement challenge agree middle.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (251,'North set medical expert.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (252,'Certain inside toward the.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (253,'Body star treat team.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (254,'Bed prove actually.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (255,'Early pick attack when create month.','pulizia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (256,'Deal serve early Mrs five.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (257,'Return bank natural high interest.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (258,'Bring traditional but on report.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (259,'Public song participant western.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (260,'Memory American remain ability watch.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (261,'Finish collection tree article.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (262,'According where article feeling western follow.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (263,'Way power occur.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (264,'Suddenly forget red service none media.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (265,'Community loss help.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (266,'Middle follow half forget former me.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (267,'Ahead democratic act available.','pulizia','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (268,'Run former minute.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (269,'Majority likely technology.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (270,'Staff have finish million.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (271,'Argue second hot yes store teach.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (272,'Language history inside environmental season environmental.','libri','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (273,'Shake painting paper team your environment.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (274,'Let goal worry popular fire rest.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (275,'Age chair friend quality manager box.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (276,'Field western budget race race rock.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (277,'Care add beat.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (278,'One ready truth full.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (279,'Down bank fall skin owner campaign.','mobilia','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (280,'Speak lawyer read fear partner.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (281,'First level theory spring beautiful.','informatica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (282,'Them forward year prove trip.','informatica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (283,'Section lawyer ok set sister hotel.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (284,'Morning order anything college street election.','cancelleria','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (285,'Bed she admit operation outside appear program.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (286,'Research staff paper.','elettronica','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (287,'Save answer increase suffer or great.','informatica','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (288,'Short hotel page member radio.','pulizia','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (289,'Heavy population draw.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (290,'Media whom official difference middle.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (291,'Continue check event task.','cancelleria','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (292,'Leave air response base meet challenge.','libri','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (293,'Top federal upon bag start administration.','cancelleria','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (294,'Situation training two quality.','elettronica','l');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (295,'Thought particular management enter.','cancelleria','m');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (296,'Natural often hand condition much PM.','elettronica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (297,'Decide writer argue.','informatica','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (298,'Recent law look training morning either.','pulizia','kg');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (299,'Kid eye wife allow sound.','libri','cad');
INSERT INTO Articolo(Codice,Descrizione,Classe,UnitaDiMisura) VALUES (300,'Discover financial before.','libri','kg');
