INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CIOIEN','Environment page south another term fly.','QCKEVP30O49O911Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MZDKIR','Whom country operation increase ten.','ABNAQC09I58B081Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AHPNKJ','Wind field especially anyone fight.','HWRZLV06E46R786O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DQPGIO','Several throw I strong.','CCXZUV63X93F834V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PTPELG','Challenge society garden open store kind.','RHLWNV97H43E805M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QXBBNH','They where our really black.','KWBTWB03Y52G945I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SIJTBK','Guess cold easy bank.','DKOUYP48P65W059D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OJOTDS','Benefit project above situation official especially green.','QCUBFO04L41G732R');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JWYLQV','Never trade wish decide boy write.','TZACOD92Y95E245B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NACPUN','Safe son strong.','XGJXSY59B46J787R');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CFSBIS','During culture participant.','ZKDLAK78A53U988N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XYWYWF','During traditional minute suffer wrong.','OAVPZW86Y51Y010F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OLMHAA','Dream character until.','COUTLE07S98Q002Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FXUYJT','Close once war start artist.','PRCSIG93H05V716R');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CQTPDK','Really point character with quickly.','LSNROE13B40B152Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZVSHKY','Morning job who find.','VQHIWF35N87X613G');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NTRQTP','Difficult skill rock safe.','FHSKBX51Q40C893U');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WNXPUV','Anything industry thousand listen new.','LIVMCU61D01D112C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CQZVOZ','Head research offer old spring.','ZGKDDX53R23S976E');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JWBANE','Speak TV she candidate everything protect.','QMTJEU95J36B001V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZKKRDR','Manage ground indeed five.','JVAQRR92B38S193M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CTYNIJ','Family there then decide.','YRKVWP65D75Z596U');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SDUTEZ','To continue financial imagine along garden.','DFHROB60R81H093T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AGYTSB','Tv affect within interesting throughout since.','BIUKCE31L25B811U');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JXUIWI','Catch movement community.','RBHCDA16L89S807J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OXKEFL','Type serve nice watch enjoy.','QCKEVP30O49O911Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VNHQRS','Use including call talk join.','ABNAQC09I58B081Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('POIOIF','Instead act total suddenly.','HWRZLV06E46R786O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JNPHLQ','Dinner door street rest.','CCXZUV63X93F834V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZDMNFO','Describe laugh against country.','RHLWNV97H43E805M');
