INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('HUDWCI','Find according newspaper event professor.','IFNSDM33F60I388Q');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DTQGKR','Experience where evening politics discover.','QPEAUZ36C26P486Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JFADWH','Later window too according various television.','UJEVBN85Q01J654Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PMYGUA','Create building college west.','RJLDTW12C00S236I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AHQEML','Item first lead beautiful certain simple.','QTCCKC78I40M146N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('KTZWBN','Child of organization hotel.','QQIJEH00H35H669C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FLBDJD','Us second fear firm design.','ZFPOJB76U56K791I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AYHVDX','Talk not important trade call woman.','WNITIE19P56K890C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MUEVAT','Think it really ground special.','RAOQVQ33A25V245Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MCHPDM','Record of contain.','TQHCCV61H96O249S');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZIRMDC','Our difference example usually.','BUMHSC75F77K179W');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NZUCDQ','In international high beautiful down happen.','KLWEWA00V62N958M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NLZXJH','Run group huge much.','GEOBHY10B90I615I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PSOMQG','Later range smile star attention.','GXDTEH44K24W375E');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('TJMYSF','Relate meeting cost beautiful.','JMVUZE52K16C863J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SUJIUR','Argue event pay who.','LVAXNP81B62I663E');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CUFARB','Another consumer receive determine newspaper summer.','SMYUKA80E19I051B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VSNOJR','The fact ever short support take keep.','SGTAZP82N97K965T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('LHXULL','Instead window simple.','WBVFIG94Y53K746H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WRXVUC','Dog support often especially.','OTCOHN94B16N555J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VRNOQK','Analysis lead lead stock five business.','AYOZGO12V99B823H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DONGYJ','Full food present baby.','JUXWQC31O05D703U');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('YLQFGU','World with perhaps force child.','VTVULH03F33Y798G');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AENXLW','Black hit much.','JBMDQK50D33K134C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('HJOFKV','Simply few others.','MWLXUI28H99N566N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WHVICI','Task least along tell evidence.','IFNSDM33F60I388Q');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('XCFIAP','Will decide authority statement also.','QPEAUZ36C26P486Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PPJMZD','Also machine really line feel able piece.','UJEVBN85Q01J654Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NVWKWO','Time require water.','RJLDTW12C00S236I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SNRFNR','Better any central with serve.','QTCCKC78I40M146N');
