INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('BSGRTS','Security morning scene interest series.','IJWRXG37C30S957T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FQZVMA','Ten while should different.','NWEECX34C92W325H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MHCPTP','Low church population.','KAPIZT42Z93V644P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('UTKSFK','Site should letter.','WYBYHK06O66H893T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('YCEZMM','Laugh window dark knowledge professional step.','CAGLSO20Q93A491J');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NHFKRL','Look who form.','VYXQOR30N67U208B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DKCXBZ','Without consider much.','XBYHIP62N20S291L');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AALCAP','Development sometimes design.','EPZHBW22P42F249T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('FNQKCW','Better mind professor avoid development.','WFMMRP55S92S629M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PNHCXP','Develop pattern purpose allow spend.','VHSHDN46X30F275C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('AROLKP','Fill as something plan indicate.','DDVVIN26Z52N299C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JKKHZO','Who realize second first they hand.','UHRIXR97U91U089X');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('EGQCJT','Reduce now lead politics trade article.','JHZVTE81Z73C335P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('IXNIIK','Pay as remain common sport.','HISCTJ36H39B235H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NSLXZU','Operation nothing economic worker value walk.','FRCYAO96C94Y452T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WITCIO','He degree American young interest.','FISYYH69P51C499H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('WERIEU','Success mouth fact.','RYJIBC84P65C924T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MZWUID','Throw get art industry.','BQSFQG06R65V745V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QAEEPP','Simple administration including situation recently.','QCIWNX33E86Y971H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('MYXUSS','Center compare reach fly bad.','YDZGUU77P96J856G');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('COJCJV','Company guy case stay.','KHEGAL89E10X828C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PMBPKY','Democrat one page experience join.','MFCRWT75V19Q125X');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('TNEIOQ','Instead final score nice.','ODUVCG62U76L043B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RQARWP','Work on worker team reflect.','QJYIOS93L08L323C');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OJFQTH','Production size this message smile.','YJKPDP69X99T951N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('BZSFCF','Hotel word explain can here.','IJWRXG37C30S957T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DRWPVB','Drop enjoy choice.','NWEECX34C92W325H');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('OBBCEG','Exactly step go.','KAPIZT42Z93V644P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RKINKY','Person lot popular high pass smile.','WYBYHK06O66H893T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SQGOMU','Sense than each.','CAGLSO20Q93A491J');
