INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OCHDVW02W20Y801M','Brittney','Erickson','1951-08-25','Port Anthony');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('SKRFIQ71Q35T230L','Kevin','Stevens','1976-11-02','Contreraschester');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CUSSKY94B67Y154U','Susan','Shields','1966-02-24','North Aprilborough');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ECFKHV90S06T725U','Alexander','Wright','1961-03-01','Palmerbury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZKZQSS24W44W681D','Amy','Lee','1992-09-21','East Christinaborough');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IAZXWF03Q86O877V','Tamara','Jensen','1966-09-29','New Heatherburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HYOWYD60I69R003M','James','Fuentes','1955-09-01','Brennanstad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AOMOAI76K68Q646W','Christine','Gonzalez','1971-05-02','Ericborough');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CKOSRC96A65J589U','Mary','Ward','2001-04-23','Ashleyshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FIHNFS50U07U081E','Daniel','Cunningham','1993-07-27','West Jeffrey');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XINMZT61R44J978R','Martha','Simmons','1971-01-21','Grantview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YIDLBD81P69S208I','Michael','Ingram','1952-07-24','Kaylaport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WVRRXO45H07E807Y','Bob','Kelly','1960-01-31','North Austin');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HEXRVR05U95M421I','Cody','Rivera','1994-01-12','New Jonathan');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NRFWQD87N45D771T','Blake','Pitts','1983-12-18','Cainview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TOCIRU66M94N309G','Mallory','Serrano','1969-02-25','Hollyburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QTUNZO03F63G773G','Timothy','Jenkins','1954-09-22','New Martin');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JPFNAK45K79E888E','Samuel','Cortez','1953-11-16','West Susanburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WAJPUA90D70C103J','Brandon','Shah','1968-03-05','Adkinsbury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YMUWGJ60I16D269D','Melissa','Haley','2000-12-29','Watsonhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OSAGOT12W76O649U','Dorothy','Wagner','2000-08-22','North David');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ITEVUO34V75R294X','Jessica','Briggs','1974-06-14','North Theodore');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JWBOFP17L55K003I','Marissa','Conner','1990-07-07','Lake Heatherfurt');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BMWOUP08K00I001Z','Martin','Zimmerman','1995-04-03','Stacyland');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FBTAAQ77F02C263R','Anna','Booth','1987-04-10','Pateltown');
