INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IFNSDM33F60I388Q','Mary','Harris','2000-02-21','Jenniferville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QPEAUZ36C26P486Z','Derrick','James','1959-06-18','Smithshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UJEVBN85Q01J654Z','Alexis','Carter','1991-08-25','Dominiqueton');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RJLDTW12C00S236I','Timothy','Jenkins','1996-07-25','New Karen');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QTCCKC78I40M146N','David','Reyes','1989-09-20','West Jenniferside');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QQIJEH00H35H669C','Nathan','Huynh','1989-01-12','Thomasberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZFPOJB76U56K791I','Dustin','Cole','1961-06-13','South Derekport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WNITIE19P56K890C','Patricia','Giles','1965-04-17','Ericside');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RAOQVQ33A25V245Y','Robert','Bailey','1995-05-24','Meganberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TQHCCV61H96O249S','Christopher','Horn','1995-12-27','Smithview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BUMHSC75F77K179W','Michael','Collins','1964-08-25','Williestad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KLWEWA00V62N958M','Crystal','Young','1960-07-19','Morriston');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GEOBHY10B90I615I','Susan','Wilkins','1962-06-03','Jacobville');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GXDTEH44K24W375E','Alyssa','Green','1994-04-26','Francisland');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JMVUZE52K16C863J','Christopher','Olson','1972-05-14','Thompsonbury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LVAXNP81B62I663E','Shannon','Norton','1956-05-27','Meadowsfort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('SMYUKA80E19I051B','Heather','Thomas','1989-03-27','Wagnermouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('SGTAZP82N97K965T','Sophia','Ford','1958-11-03','Mercadofort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WBVFIG94Y53K746H','Ricky','Kane','1981-07-12','West Arthur');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OTCOHN94B16N555J','Thomas','Williamson','1982-05-12','Carolynburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AYOZGO12V99B823H','Brandon','Robles','1979-01-06','East Daniel');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JUXWQC31O05D703U','Allen','May','1952-10-07','Wilsonview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VTVULH03F33Y798G','Tamara','Martinez','1965-10-11','New Andrew');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JBMDQK50D33K134C','Hunter','Wang','1958-05-11','Dyerfurt');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MWLXUI28H99N566N','Tony','Woodard','1957-06-30','East Melissa');
