INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IJWRXG37C30S957T','Patricia','Reid','1970-04-17','West Gerald');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NWEECX34C92W325H','Dustin','Cline','1959-05-17','West Markshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KAPIZT42Z93V644P','Tiffany','Wallace','1972-07-01','East Jessicabury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WYBYHK06O66H893T','Frances','Galloway','1984-02-25','Nancybury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CAGLSO20Q93A491J','Jeffrey','Boyer','1962-08-05','Marksport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VYXQOR30N67U208B','Emma','Williams','1957-02-18','Thomasfort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XBYHIP62N20S291L','Edward','Hernandez','1985-06-24','West Heathermouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EPZHBW22P42F249T','Kevin','Brown','1995-04-18','Spencerhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WFMMRP55S92S629M','Amy','Ramos','1965-01-08','Veronicabury');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VHSHDN46X30F275C','Jennifer','Shepard','1969-11-10','New Markstad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DDVVIN26Z52N299C','Austin','Singh','1993-03-30','Lambertshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UHRIXR97U91U089X','Heather','Moody','1996-08-24','Lake Danielhaven');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JHZVTE81Z73C335P','Ross','Hale','1962-09-04','New Diane');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HISCTJ36H39B235H','Tammy','Moore','1970-12-02','Zacharyberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FRCYAO96C94Y452T','Valerie','Bridges','1990-11-24','Bakerland');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FISYYH69P51C499H','Laurie','Gallagher','1955-07-09','East Emilystad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RYJIBC84P65C924T','Lori','Davis','1957-04-17','North Joycemouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BQSFQG06R65V745V','Keith','Kirk','1996-11-09','Port Katherinechester');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QCIWNX33E86Y971H','Jeffrey','Hardy','1965-04-12','Port Bobbyborough');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YDZGUU77P96J856G','Elizabeth','Lewis','1988-12-07','Saraview');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KHEGAL89E10X828C','James','Kim','1963-08-12','West Michelle');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MFCRWT75V19Q125X','Gail','Casey','1987-12-21','Terryshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ODUVCG62U76L043B','Alexandra','Green','2000-08-24','Brandonport');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QJYIOS93L08L323C','Jesse','Mitchell','1999-01-31','South Eugene');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YJKPDP69X99T951N','Andrew','Kennedy','1961-11-18','Ericksonland');
