#!/bin/bash

clear;

chars="/-\|"

spin(){
	while kill -0 $2 > /dev/null 2>&1; 
	do
	  for (( i=0; i<${#chars}; i++ )); do
		sleep 0.5
		echo -en "\t ${chars:$i:1} $1" "\r"
	  done
	done
	wait $2
	code=$?
	if [[ $code -eq 0 ]]; then
		echo -e "\r\t✅"
	else
		tput bold; echo "\nAn error occoured\n"; tput sgr0
		exit 1;
	fi
}

DB_CREATION=create_db.sql
MOCKUP_DATA=./sql
DATABASE=ufficioacquisti
export PGPASSWORD="bdd2021"

echo; 

tput bold; echo -en "\rCreating db"; tput sgr0
(psql -U postgres -h localhost -p 15000 -c "drop database if exists $DATABASE") > /dev/null 2>&1
(createdb -U postgres -h localhost -p 15000 $DATABASE) > /dev/null

tput bold; echo -en "\rBuilding database"; tput sgr0
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f $DB_CREATION) > /dev/null

tput bold; echo -en "\rMockup Data Insertion\n\n"; tput sgr0

(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Responsabile.sql") > /dev/null &
spin Reponsabile $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Dipartimento.sql") > /dev/null &
spin Dipartimento $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Articolo.sql") > /dev/null &
spin Articolo $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Fornitore.sql") > /dev/null &
spin Fornitore $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/RecapitoTelefonico.sql") > /dev/null &
spin RecapitoTelefonico $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Fornisce.sql") > /dev/null &
spin Fornisce $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/RichiestaAcquisto.sql") > /dev/null &
spin Fornisce $!
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Ordine.sql") > /dev/null &
spin Ordine $! 
(psql -U postgres -h localhost -p 15000 -d $DATABASE -f "$MOCKUP_DATA/Include.sql") > /dev/null &
spin Include $! 

echo; echo;

echo -e "Bye\n"

