version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "15000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: bdd2021