INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FLOVPL59N35U627F','Alizée','Lowy','23-03-1963','Dūst Moḩammad Khān');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MXLFBK18U77H568H','Andrée','Blaza','15-12-1997','Tolotangga');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OTONYB14V08E157U','Björn','Moquin','06-02-1952','Revelstoke');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QJGNZD15T70S863F','Kù','Touret','09-02-1984','Alca');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LNEOEO86D67R378O','Loïca','McNish','29-05-1966','Kerek');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FDPSLX08Q49W797X','Géraldine','MacRannell','29-08-1996','Bārah');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HBRFQT69L61B556D','Lóng','Van der Kruijs','30-06-1952','Verin Dvin');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('SIJXDS84P06K180V','Maëlla','Spat','03-12-1973','San Carlos');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XFGUCY39Q73Z813D','Stéphanie','Partridge','29-04-1982','Eldoret');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BKQDYF39W51A931S','Vénus','Withinshaw','07-04-1993','Fengshan');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ENGWHK60W66T779G','Bérangère','Dugmore','02-10-1952','Žiežmariai');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PBMNWD60A88K678U','Renée','Allen','25-10-1972','São Francisco');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XUCEGS88D49W608I','Mahélie','Bytheway','02-09-1965','Bonga');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WNCSBQ78Y60H500X','Maéna','Davidovicz','29-04-1997','Khosta');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QGKVQO81B70B279U','Amélie','Stockall','23-10-1973','Pucheng');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JVHQBZ17W18J250P','Liè','Houston','22-08-1964','Kašina');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DZEAOG80F93E920L','Athéna','Gheorghie','01-08-1981','Konstantinovo');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DWTMWS68R28E022U','Béatrice','Wedmore','16-09-1993','Blagoveshchensk');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CIZDKY95B34A556X','Táng','O''Heyne','04-06-1953','Pirava');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CTVJVG31K73N732J','Maéna','Carlone','11-01-1961','Jīt');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XCMHAK21T97I547U','Mélissandre','MacIllrick','07-03-1987','Jambean');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AUZBLT69L86Z205T','Josée','Growy','28-04-1975','Sukhothai');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZQHKIT80D06M483M','Lucrèce','Pohlak','14-03-1977','Täby');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WWYRWK83S15R810X','Hélèna','Blaymires','19-05-1950','Kafir Qala');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EEVBRE21A81W726N','Loïca','Strettell','07-08-1961','Ravānsar');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZIPRBN84D70Q246P','Maéna','Tranfield','02-03-1976','Sangtian');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HWUSAU41G24Y787X','Adèle','Lotze','24-12-1991','Shipaidong');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DHPCXS02R64O627C','Réjane','Walklott','24-04-1979','Ebak');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ZMJFUD77A16O244X','Börje','McNirlin','15-01-1992','Matumadua');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LKJRNE22L88X480B','Bérengère','Scimoni','08-09-1954','Claresholm');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BPAAQC28O51J712G','Alizée','Cornick','16-04-1952','Flers');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VEQQUJ20A59T222Z','Nuó','Cullabine','13-04-1976','Wuli');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KWWCKM65U93Z439K','Björn','Duigan','26-07-1971','Hudson Bay');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FQPGUO09H16X873Q','Félicie','Herrieven','27-11-1957','Kax');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NLRSVQ19G52H137F','Pò','Andreopolos','05-09-1991','Lere');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KFFZCA84E96P473N','Mylène','Tantrum','07-09-1975','Rožaje');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XLWEIN65X53T543V','Adélaïde','Saw','19-12-1999','Lagyná');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XIWIGS07U21C302U','Michèle','Broschke','31-10-1955','Parnamirim');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IQRRFC15B92X715H','Françoise','Le Teve','11-04-1980','Vília');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LUUERV66M12K086K','Daphnée','Gladyer','05-12-1955','Macarse');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('UTKYXW85S34E399X','Clémence','Purdom','23-07-1997','Anbyŏn-ŭp');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RJUSLB89Z06K178I','Marie-ève','Witnall','07-11-1964','Dabaozi');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QQSLLT60C72O481J','Maëline','Luc','24-03-1992','Kolomyya');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JXOZAH23I24N508C','Séverine','O''Fearguise','11-12-1982','Made');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('RTPGUT60Z29Q749M','Félicie','Lyburn','30-12-1970','Registro');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TOBGCA93Y22V682L','Cinéma','Jorioz','16-09-1971','Energeticheskiy');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HIFDJN06S11E678C','Laurélie','Linskill','13-09-1996','Aisai');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DMXRLK51H91U456K','Pélagie','Greggs','11-03-1981','Tanjung');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('SHITGM70T24B235C','Clémentine','Walwood','25-02-1987','Rotterdam postbusnummers');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PHIJNV31L30H707S','Mélina','Clues','10-09-1991','Svay Rieng');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TTBRVH82L62G963X','Illustrée','Aronov','12-01-1988','Ma’ao');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WPSZMZ55F29D152S','Gaétane','Rupel','31-10-1970','Foxrock');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ICDXZM04F70I547H','Mélodie','Damant','01-03-1950','Mandōl');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('AUPWBK88V84O047G','Réservés','Muffen','15-10-1951','Guangyubao');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LRQFGG30L11T350Q','Estève','Auty','27-08-1989','Zhongshanlu');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('APMCOF36Z90Z095H','Maëly','Boston','29-08-1984','Bajiao');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BLHKDC38N18I319K','Pélagie','Pagen','23-02-1991','Newark');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DSEXET38W43Y201P','Marie-hélène','McEachern','08-08-1975','Bazi');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TRGUGO64H43G301R','Thérèsa','Rickword','12-03-1975','Pilzno');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MRLRPD96E67J422G','Vérane','Ricardin','15-05-1974','Périgueux');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GHOFJV19B30O499Z','Hélèna','Espine','07-01-1973','Quanjiang');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GZVTHJ53X71Z065K','Pélagie','Dany','01-02-1966','Kanaya');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PNWDVG94V62V044H','Laurélie','Inkle','17-08-1994','Birni N Konni');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EXQQUX31H97J607D','Judicaël','Haile','17-04-1963','Kempele');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PTNNWC65E75C726Q','Yóu','Larderot','06-05-1959','Ústí nad Labem');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('STKMRX26Y37F753K','Gaïa','Chyuerton','04-12-1999','Bader');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KOMJGL93S83F201M','Noëlla','Illingworth','16-03-1991','Potęgowo');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('LWSXBW52L53Q720G','Eugénie','McGlew','12-09-1963','Puerto Parra');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('QBWUOR68T88K489O','Loïca','Mayne','28-12-1970','Bagnères-de-Bigorre');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EQKBTP14D42F245S','Pò','Combes','29-04-1999','Karatsu');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BOVSVV00Q70F654A','Rébecca','Zuenelli','27-03-1996','Boaco');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OZCVGZ85E96M460W','Magdalène','Philipet','22-01-1995','Belos Ares');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FHOBXD48H27C868K','Eléa','Dunbobin','21-03-1951','Thị Trấn Bắc Hà');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('DGSYAM97D60L466J','Valérie','Jedrych','02-12-1950','Pecatu');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('MHQZZN61Q09Z432Y','Daphnée','Ponsford','16-08-1956','Kashima-shi');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GIQJDE70S78I696T','Ráo','Axston','15-02-1981','Bileća');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KNJMSW53D59K202R','Stévina','Scutcheon','01-10-1999','Gorodishche');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GARQDO58S31M625Y','Marie-ève','Brownsall','29-04-1991','Campo Viera');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NAJURX09C26I008K','Ruò','Vell','15-04-1972','Pittsburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YHTBHN76B09X988B','Marie-hélène','Ashbee','31-07-1987','Nakhon Luang');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JZDHMM79S87N728B','Lóng','Cockland','24-09-1967','Doloplazy');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XRESHX81T29O111J','Liè','Dunlop','07-04-1983','El Limon');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('VZOCRS09F02K566T','Intéressant','Baylie','17-12-1987','Fengjiang');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WKYPZK33H27J151T','Daphnée','Mardle','03-05-1980','Nova Granada');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YCJWQD25S18D083W','Wá','Mathys','23-10-1964','Bertioga');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('OXNAUV53E85I523O','Andréanne','Emanuelov','13-10-1976','Los Angeles');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JHAKNH73E81N260Y','Eléonore','Brightling','09-11-1998','Shamboyacu');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KGYJNG78I82O040M','Eloïse','Lenormand','15-12-1982','Sacsamarca');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BTKXAP70Z13P925X','Marlène','Allsep','19-07-1998','Qiujia');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CWXNMN78A91N667C','Méng','McMichan','06-03-1950','Bakungan');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('NPYPGZ59P77T722J','Maëlle','Corgenvin','27-12-1978','Calangain');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FSXCPO84Q79A860O','Camélia','Kunz','30-04-1994','Silago');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TNXMCB90P05R302M','Bécassine','Sinnocke','18-01-1988','Kota Kinabalu');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HGKIAQ31Q81W837R','Thérèse','Botterell','26-12-1995','Bačka Topola');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JPRRQU24N31A752Q','Lóng','Spandley','22-03-1967','General Alvear');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('GDLZFS85O68J993Y','Kù','Tommasetti','05-10-1976','Yinchuan');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FEABNF14V32I289T','Kévina','Ghione','25-10-1986','Panikian');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('EWACTB98K27O626A','Laurène','Moffet','26-09-1974','Lesnoy');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('THFXAI03U98B700N','Mylène','Pickard','11-07-1953','Jinpanling');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WQKAHY09E37J979N','Agnès','Benson','30-11-1959','Labuhankananga');
