---
title: "Analisi del database"
output: html_notebook
editor_options:
chunk_output_type: inline
---


```{r Libraries}
library("ggplot2")
library("RPostgreSQL")
library("dplyr")
library("scales")
library("ggrepel")
library("stringr")

custom_colours <- c("cancelleria" = "#463480", "pulizia" = "#32658e", "libri" = "#218e8d", "informatica" = "#33b67a", "elettronica" = "#8dd645", "mobilia" = "#fde725")
```

```{r Connection setup}
drv <- dbDriver("PostgreSQL")
con <- dbConnect(
  drv,
  dbname = "ufficioacquisti",
  host = "localhost",
  port = 15000,
  user = "postgres",
  password = "bdd2021"
)
```
```{r Distribuzione delle classi}
distribuzione_classi <- dbGetQuery(con, "select classe, count(*)/(sum(count(*)) over()) as frequenza from articolo group by classe;")

distribuzione_classi <- distribuzione_classi %>%
  arrange(classe) %>%
  mutate(
    pos = frequenza / 2 + lead(rev(cumsum(rev(frequenza))), 1),
    pos = if_else(is.na(pos), frequenza / 2, pos)
  )

ggplot(distribuzione_classi, aes(x = 1, y = frequenza, fill = classe)) +
  geom_col() +
  coord_polar("y", start = 0) +
  geom_label(aes(label = paste0(str_to_title(classe), "\n", percent(frequenza)), y = pos), size = 4, nudge_x = 1) +
  scale_fill_manual(values = custom_colours) +
  theme_void() +
  theme(legend.position = "none")

ggsave("./R/analysisPlots/distribuzione_classi.png", width = 7.5)
```
```{r Distribuzione dei fornitori per gli articoli}
distribuzione_articoli_fornitore <- dbGetQuery(con, "select fornitore, classe, count(*) as frequenza from fornisce as f join (select codice, classe from articolo) as a on f.articolo = a.codice group by fornitore, classe;")

ggplot(distribuzione_articoli_fornitore, aes(x = reorder(fornitore, -frequenza, sum), y = frequenza, fill = reorder(classe, frequenza))) +
  geom_col() +
  xlab("Fornitore") +
  ylab("Numero articoli forniti") +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 40), expand = c(0, 0), limits = c(0, 220)) +
  labs(fill = "Classi merceologiche") +
  scale_fill_manual(values = custom_colours)

ggsave("./R/analysisPlots/distribuzione_articoli_fornitore.png", width = 7.5)

```
```{r Confronto della spesa per dipartimento in base alla classe}
spesa_dipartimento_classe <- dbGetQuery(con, "select dipartimento, classe, sum(quantita * prezzounitario) as spesa from include i join (select codice, classe from articolo) a on i.articolo = a.codice group by dipartimento, classe;")

ggplot(spesa_dipartimento_classe, aes(x = dipartimento, y = spesa, fill = classe)) +
  geom_col(position = "dodge") +
  scale_fill_viridis_d(begin = 0.15, option = "H") +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 40), expand = c(0, 0)) +
  xlab("Fornitore") +
  ylab("Spesa [€]") +
  labs(fill = "Classi merceologiche")
ggsave("./R/analysisPlots/spesa_dipartimento_classe.png")
```
```{r Divisione della spesa totale dei dipartimenti in base alla classe merceologica}
spesa_classe <- dbGetQuery(con, "select classe, sum((quantita * prezzounitario)/1000000) as spesa, sum((quantita * prezzounitario)/1000000)/(sum(sum((quantita * prezzounitario)/1000000)) over()) as frequenza from include i join (select codice, classe from articolo) a on i.articolo = a.codice group by classe;")

ggplot(spesa_classe, aes(x = reorder(classe, -spesa), y = spesa, fill = classe)) +
  geom_col() +
  scale_fill_manual(values = custom_colours) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 40), expand = c(0, 0)) +
  xlab("Classi merceologiche") +
  ylab("Spesa [milioni di €]") +
  labs(fill = "Classi merceologiche")
ggsave("./R/analysisPlots/spesa_classe.png", width = 7.5)

spesa_classe <- spesa_classe %>%
  arrange(classe) %>%
  mutate(
    pos = frequenza / 2 + lead(rev(cumsum(rev(frequenza))), 1),
    pos = if_else(is.na(pos), frequenza / 2, pos)
  )

ggplot(spesa_classe, aes(x = 1, y = frequenza, fill = classe)) +
  geom_col() +
  coord_polar("y", start = 0) +
  geom_label(aes(label = paste0(str_to_title(classe), "\n", percent(frequenza)), y = pos), size = 4, nudge_x = 1) +
  scale_fill_manual(values = custom_colours) +
  theme_void() +
  theme(legend.position = "none")
ggsave("./R/analysisPlots/spesa_classe_pie.png")
```
```{r Richieste effettuate ogni trimestre dai dipartimenti}
richieste_dipartimento_trimestre <- dbGetQuery(
        con,
        "
          select dipartimento, count(*) numerorichieste, case
            when extract(month from dataemissione) < 4 then 1
            when extract(month from dataemissione) < 7 then 2
            when extract(month from dataemissione) < 10 then 3
            else 4 end trimestre
          from richiestaacquisto
          group by dipartimento, trimestre
           order by trimestre, numeroRichieste;
        ")
myPalette <- c("#5a54b6",
               "#cd7d2d",
               "#006d10",
               "#ff7f5f",
               "#900019",
               "#ff86de",
               "#02d691",
               "#abfb8a",
               "#ff5b98",
               "#d07b00",
               "#56007f",
               "#c1a700",
               "#76a700",
               "#00279e",
               "#d10086",
               "#ed9e00",
               "#fd7dff",
               "#7671ff",
               "#e70045",
               "#cc69ff",
               "#99ff5d",
               "#ffdc0f",
               "#ff45db",
               "#eeef09",
               "#00cc34",
               "#97e200",
               "#7400b8",
               "#a0ff33",
               "#f2000d",
               "#d936ea")
ggplot(richieste_dipartimento_trimestre, aes(fill = dipartimento, x = trimestre, y = numerorichieste)) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = myPalette) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 20), expand = c(0, 0)) +
  xlab("Trimestre") +
  ylab("Numero di richieste") +
  labs(fill = "Dipartimento")

ggsave("./R/analysisPlots/richieste_dipartimento_trimestre.png")
```
```{r Richieste effettuate ogni mese}
richieste_mensili <- dbGetQuery(con, "select extract(month from dataemissione) mese, count(*) numerorichieste from richiestaacquisto group by mese order by mese;")

ggplot(richieste_mensili, aes(x = factor(mese), y = numerorichieste, fill = factor(mese))) +
  geom_col() +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 20), expand = c(0, 0)) +
  xlab("Mese") +
  ylab("Numero di richieste") +
  labs(fill = "Mese")
ggsave("./R/analysisPlots/richieste_mensili.png")
```
```{r}
spesa_dipartimenti_giugno <- dbGetQuery(
        con,
        "
        select i.dipartimento, sum((quantita * prezzounitario)) spesa
        from include i
          join (select dipartimento, numero, dataemissione from richiestaacquisto) r on r.dipartimento = i.dipartimento and r.numero = i.numerorichiesta
        where extract(month from dataemissione) = 6
        group by i.dipartimento
        order by i.dipartimento;
      ")

ggplot(spesa_dipartimenti_giugno, aes(fill = dipartimento, x = reorder(dipartimento, -spesa), y = spesa)) +
  geom_col() +
  scale_fill_manual(values = myPalette) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 40), expand = c(0, 0)) +
  xlab("Dipartimento") +
  ylab("Spesa [€]") +
  labs(fill = "Dipartimento")
ggsave("./R/analysisPlots/spesa_dipartimento_giugno.png")
```
```{r  Spesa giornagliera dei dipartimenti nell'anno 2020}
spesa_giornagliera_dipartimenti <- dbGetQuery(
        con,
        "
        select i.dipartimento, numerorichiesta, sum((quantita * prezzounitario)) spesa
        from include i
          join (select dipartimento, numero, dataemissione from richiestaacquisto) r on r.dipartimento = i.dipartimento and r.numero = i.numerorichiesta
        group by i.dipartimento, i.numerorichiesta
        order by i.dipartimento, i.numerorichiesta;
      ")

ggplot(spesa_giornagliera_dipartimenti, aes(fill = dipartimento, x = reorder(dipartimento, -spesa), y = spesa)) +
  geom_boxplot() +
  scale_fill_manual(values = myPalette) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 40), expand = c(0, 0)) +
  xlab("Dipartimento") +
  ylab("Spesa [€]") +
  labs(fill = "Dipartimento")
ggsave("./R/analysisPlots/spesa_giornagliera_dipartimenti.png")
```
