INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('TEBLJF','Time maintain example reality knowledge whatever explain.','FQJEZA11E84H509P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZHTHMA','Stay must imagine carry skill.','IMKBVX60O36X135Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ZNBEEY','Food interview much stuff nothing.','CRXDGE80Y81O389F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CPNVKS','Worry citizen prevent join continue better.','CTAXXL63A24A933V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('LMDFFB','Message art more dark.','ULWMFI65Q94N579I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DNTZMS','Partner though front.','KFUYMK18Q13W724D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('BWNNDW','Guy together success reality.','YFZXDP94I45W954A');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QZABSF','Beautiful popular arm appear marriage board.','ECBMTA40N06A296L');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('CAYMVS','Matter join hospital.','JDBJAM08V68Z749N');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('PECQWS','Game body quality.','FNNHNA39R67B920B');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('EHPCDP','Challenge how beautiful task expert customer.','XFSYBQ61E87O521V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('YVSVOK','Blue actually hundred employee respond.','YUARGH84U71J463D');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('NHNQQX','Organization pretty remember.','CNOYME75H15W622I');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DNSHJR','Tend little born create.','IZZWHV83X46L567M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('GAGEYE','Within tend visit tree to.','BVDLKY38J99E892Y');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JMHOLD','Cover Mrs student.','XNXGEP23Z26B175T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VZHTWA','Store which fine.','PTJULB51X62J472U');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('KQSKTO','Third investment message number hope.','KRCYOV87D66Y157W');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('RICWFZ','Rock add investment police.','TQWRUC63W44D809T');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('QETNBQ','Finish our industry.','HKQBLF06T83N596O');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('ANJCLJ','Ago leg health perform specific.','WDAMSV43P11E326L');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('TMKYYP','Perform begin citizen rate.','YQEJYB22B70U175P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('SZEQEV','Body material arrive which.','CEGTMC61F62U477M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('JMYWMF','Kind man billion find arrive.','TIQGMR12L41W433K');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('URDKJB','Can walk who.','KEKADY03B97U525M');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('DKAOKP','Worker use pressure foot for.','FQJEZA11E84H509P');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('VOYRVJ','Them effort it part establish.','IMKBVX60O36X135Z');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('UPKWOF','Range information act.','CRXDGE80Y81O389F');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('GNNMXO','Wonder single serious trip.','CTAXXL63A24A933V');
INSERT INTO Dipartimento(Codice,Descrizione,Responsabile) VALUES ('HLCJLX','Media forward add whom focus she.','ULWMFI65Q94N579I');
