INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FQJEZA11E84H509P','Christopher','Weeks','1960-11-11','Scottmouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IMKBVX60O36X135Z','Robert','Hernandez','1975-10-06','Deborahstad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CRXDGE80Y81O389F','Steven','Harris','1953-04-11','Port Michael');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CTAXXL63A24A933V','Beth','Guzman','1979-08-18','South Johnathan');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ULWMFI65Q94N579I','Carrie','Alvarado','1974-11-03','East Lisa');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KFUYMK18Q13W724D','Andrea','Mclean','1957-02-03','West Heathermouth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YFZXDP94I45W954A','Johnathan','Martin','1974-11-23','East Tommy');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('ECBMTA40N06A296L','Thomas','Ford','1994-03-07','Port Allison');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('JDBJAM08V68Z749N','James','Wilson','1985-10-04','North Patrickchester');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('FNNHNA39R67B920B','Fred','Booth','1954-06-02','Andrewstad');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XFSYBQ61E87O521V','Patricia','Collins','1962-02-02','Batesberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YUARGH84U71J463D','Richard','Wu','1954-12-08','Jasonburgh');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CNOYME75H15W622I','William','Wright','1991-12-08','West Adamshire');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('IZZWHV83X46L567M','Gloria','Durham','1992-06-24','Lake Barbarafort');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('BVDLKY38J99E892Y','Joshua','Torres','1973-04-06','Port Walter');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('XNXGEP23Z26B175T','James','Henderson','1995-09-26','Lake Stephanie');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('PTJULB51X62J472U','Karen','Jones','1978-01-02','South Kristenchester');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KRCYOV87D66Y157W','Jennifer','Ortiz','1973-04-10','North Jeffrey');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TQWRUC63W44D809T','Megan','Mckinney','1979-09-25','Smithborough');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('HKQBLF06T83N596O','Kristen','Merritt','1965-08-29','Lake Paulland');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('WDAMSV43P11E326L','Diana','Hunt','1970-09-19','West Matthewchester');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('YQEJYB22B70U175P','Angela','Barber','1957-01-22','Fieldsberg');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('CEGTMC61F62U477M','Jonathan','Howard','1989-12-03','West Ruth');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('TIQGMR12L41W433K','Morgan','Diaz','1981-06-04','South Nathan');
INSERT INTO Responsabile(CodiceFiscale,Nome,Cognome,DataNascita,LuogoNascita) VALUES ('KEKADY03B97U525M','Melissa','Murray','1964-10-13','South Beth');
